.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Domain/ADAccessor.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Domain/ADAccessor.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Domain\&.ADAccessor\fP"
.br
.RI "Accesses a given Active Directory server as specified in the web\&.config for retrieving additional user information "
.ti -1c
.RI "class \fBJBToolkit\&.Domain\&.ADUser\fP"
.br
.RI "Object to store user details, such as username, full name, email, job title etc and what roles and permissions they have\&. Also can get user profile image "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Domain\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
