.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/JQueryDataTableViewModels/AjaxDataTable.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/JQueryDataTableViewModels/AjaxDataTable.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.DataTableParameters\fP"
.br
.RI "Turns the Ajax call parameters into a DataTableParameter object "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.Parameters\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.DataTableColumn\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.DataTableOrder\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.DataTableSearch\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.DataTableResultSet\fP"
.br
.RI "Data returned to DataTable "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.DataTableResultError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Views\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
