.TH "Attribute" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Attribute
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystem\&.Drawing\&.Html\&.CssPropertyAttribute\fP, and \fBSystem\&.Drawing\&.Html\&.CssPropertyInheritedAttribute\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
