.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/WinForms/Helpers/ColourHelper.cs" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/WinForms/Helpers/ColourHelper.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ColourHelper\fP"
.br
.RI "Methods to convert RGB to hex, hex to RGB, alter colour brightness, lightness, intensity, also generate random 'nice' colours\&. "
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ColourHelper\&.ColourGenerator\fP"
.br
.RI "Generates random colours close to primary colours as hex string and doesn't repeat a colour "
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ColourHelper\&.PatternGenerator\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ColourHelper\&.IntensityGenerator\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ColourHelper\&.IntensityValue\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ColourHelper\&.IntensityValueWalker\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.WinForms\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
