.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/WinForms/Helpers/HtmlHelper/CssBoxWord.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/WinForms/Helpers/HtmlHelper/CssBoxWord.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSystem\&.Drawing\&.Html\&.CssBoxWord\fP"
.br
.RI "Represents a word inside an inline box "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSystem\fP"
.br
.ti -1c
.RI "namespace \fBSystem\&.Drawing\fP"
.br
.ti -1c
.RI "namespace \fBSystem\&.Drawing\&.Html\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
