.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/CSV/CSVHelper.Native.cs" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/CSV/CSVHelper.Native.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Csv\&.Native\&.CsvHelper\fP"
.br
.RI "Convert CSV from and to a DataTable\&. This class doesn't require any third party packages to use which can sometimes be useful, however it may not account for every single permutation of a CSV file, ony basic\&. This class does however support strings wrapped in 'Speachmarks' quite nicely, whic quite a lot of CSV to DataTable implementations don't seem to get right\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Csv\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Csv\&.Native\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
