.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/CSV/CSVHelper.Native.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/CSV/CSVHelper.Native.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.CSV\&.Native\&.CSVHelper\fP"
.br
.RI "Convert \fBCSV\fP from and to a DataTable\&. This class doesn't require any third party packages to use which can sometimes be useful, however it may not account for every single permutation of a \fBCSV\fP file, ony basic\&. This class does however support strings wrapped in 'Speachmarks' quite nicely, whic quite a lot of \fBCSV\fP to DataTable implementations don't seem to get right\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.CSV\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.CSV\&.Native\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
