.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/WinForms/CustomToolTip.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/WinForms/CustomToolTip.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.CustomToolTip\fP"
.br
.RI "Nicer Custom Tooltip for controls "
.ti -1c
.RI "struct \fBJBToolkit\&.WinForms\&.CustomToolTip\&.ToolTipControl\fP"
.br
.RI "Provides information about ToolTips that are associated with their controls\&. This structure is used specifically with the 'GetToolTip(control)' method\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.WinForms\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
