.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Database/DBConnection Directory Reference" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Database/DBConnection Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDBConnection\&.Dapper\&.cs\fP"
.br
.ti -1c
.RI "file \fBDBConnection\&.DBResult\&.cs\fP"
.br
.ti -1c
.RI "file \fBDBConnection\&.SQLClient\&.cs\fP"
.br
.in -1c
