.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Windows Directory Reference" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Windows Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCommonFileTypeExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBDirectoryHelper\&.cs\fP"
.br
.ti -1c
.RI "file \fBFastDirectoryEnumerator\&.cs\fP"
.br
.ti -1c
.RI "file \fBProcessHelper\&.cs\fP"
.br
.ti -1c
.RI "file \fBServiceHelper\&.cs\fP"
.br
.ti -1c
.RI "file \fBUACHelper\&.cs\fP"
.br
.ti -1c
.RI "file \fBWindowHelper\&.cs\fP"
.br
.in -1c
