.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/PdfDoc Directory Reference" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/PdfDoc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBConverters\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPdfConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBPdfMerger\&.cs\fP"
.br
.ti -1c
.RI "file \fBPdfParser\&.cs\fP"
.br
.ti -1c
.RI "file \fBPdfSplitter\&.cs\fP"
.br
.in -1c
