.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/SharePoint/CSOM/Manage Directory Reference" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/SharePoint/CSOM/Manage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCopyFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBCopyFolder\&.cs\fP"
.br
.ti -1c
.RI "file \fBCreateFolder\&.cs\fP"
.br
.ti -1c
.RI "file \fBDeleteFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBDeleteFolder\&.cs\fP"
.br
.ti -1c
.RI "file \fBDoesFileExist\&.cs\fP"
.br
.ti -1c
.RI "file \fBDoesFolderExist\&.cs\fP"
.br
.ti -1c
.RI "file \fBFileInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBMoveFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBMoveFolder\&.cs\fP"
.br
.in -1c
