.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/InterProcessComms/MemoryMappedFile Directory Reference" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/InterProcessComms/MemoryMappedFile Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMemoryMappedFilesClient\&.cs\fP"
.br
.ti -1c
.RI "file \fBMemoryMappedFilesServer\&.cs\fP"
.br
.in -1c
