.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/SharePoint/CSOM Directory Reference" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/SharePoint/CSOM Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBManage\fP"
.br
.ti -1c
.RI "directory \fBObjects\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAuthentication\&.cs\fP"
.br
.ti -1c
.RI "file \fBDownload\&.cs\fP"
.br
.ti -1c
.RI "file \fBUpload\&.cs\fP"
.br
.ti -1c
.RI "file \fBUtils\&.cs\fP"
.br
.in -1c
