.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/FuzzyLogic/Algorithms Directory Reference" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/FuzzyLogic/Algorithms Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDoubleMetaphoneAlgorithm\&.cs\fP"
.br
.ti -1c
.RI "file \fBHammingDistance\&.cs\fP"
.br
.ti -1c
.RI "file \fBJaccardDistance\&.cs\fP"
.br
.ti -1c
.RI "file \fBJaroDistance\&.cs\fP"
.br
.ti -1c
.RI "file \fBJaroWinklerDistance\&.cs\fP"
.br
.ti -1c
.RI "file \fBLevenshteinDistance\&.cs\fP"
.br
.ti -1c
.RI "file \fBLongestCommonSubsequence\&.cs\fP"
.br
.ti -1c
.RI "file \fBLongestCommonSubstring\&.cs\fP"
.br
.ti -1c
.RI "file \fBOverlapCoefficient\&.cs\fP"
.br
.ti -1c
.RI "file \fBRatcliffObershelpSimilarity\&.cs\fP"
.br
.ti -1c
.RI "file \fBSorensenDiceDistance\&.cs\fP"
.br
.ti -1c
.RI "file \fBTanimotoCoefficient\&.cs\fP"
.br
.in -1c
