.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Zip Directory Reference" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Zip Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBExtractOtherCompressedArchiveTypes\&.cs\fP"
.br
.ti -1c
.RI "file \fBZipArchive\&.Native\&.cs\fP"
.br
.ti -1c
.RI "file \fBZipCompression\&.cs\fP"
.br
.ti -1c
.RI "file \fBZipExtraction\&.cs\fP"
.br
.in -1c
