.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/InterProcessComms/Sockets Directory Reference" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/InterProcessComms/Sockets Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSocketClient\&.cs\fP"
.br
.ti -1c
.RI "file \fBSocketsServer\&.cs\fP"
.br
.in -1c
