.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/InterProcessComms Directory Reference" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/InterProcessComms Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBMemoryMappedFile\fP"
.br
.ti -1c
.RI "directory \fBMessageQueues\fP"
.br
.ti -1c
.RI "directory \fBNamedPipes\fP"
.br
.ti -1c
.RI "directory \fBNetRemoting\fP"
.br
.ti -1c
.RI "directory \fBSockets\fP"
.br
.ti -1c
.RI "directory \fBWcf\fP"
.br
.ti -1c
.RI "directory \fBWmCopyData\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIIpcContracts\&.cs\fP"
.br
.in -1c
