.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/FuzzyLogic/Generic Directory Reference" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/FuzzyLogic/Generic Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOperations\&.cs\fP"
.br
.in -1c
