.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/SharePoint/CSOM/Objects Directory Reference" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/SharePoint/CSOM/Objects Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFileFolderCollection\&.cs\fP"
.br
.in -1c
