.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Database/DataTableStates.cs" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Database/DataTableStates.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Database\&.DataTableState\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Database\&.DataTableStates\fP"
.br
.RI "For saving JQuery DataTable states (column order, column visibility, filters etc) - Saves in a provided DataBase\&. If the standard table doesn't exist this class will create it "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Database\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
