.TH "DataGridViewTextBoxCell" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataGridViewTextBoxCell
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.WinForms\&.ColorPickerCell\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
