.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/RegularExpressions/DateTimeHelper.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/RegularExpressions/DateTimeHelper.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.RegularExpressions\&.DateTimeHelper\fP"
.br
.RI "Methods for DateTime search, validation and manipulation "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.RegularExpressions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
