.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Database/DBConnection/DBConnection.DBResult.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Database/DBConnection/DBConnection.DBResult.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Database\&.DBResult\fP"
.br
.RI "Results object from a DB command "
.ti -1c
.RI "class \fBJBToolkit\&.Database\&.DBResult\&.SuccessDBCommandResult\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Database\&.DBResult\&.FailureDBCommandResult\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Database\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
