.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Windows/DirectoryHelper.cs" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Windows/DirectoryHelper.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.DirectoryHelper\fP"
.br
.RI "Class containing methods to retrieve specific file system paths\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Windows\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJBToolkit\&.Windows\&.KnownFolder\fP { \fBJBToolkit\&.Windows\&.KnownFolder\&.Contacts\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Desktop\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Documents\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Favorites\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Links\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Music\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Pictures\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.SavedGames\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.SavedSearches\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Videos\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Fonts\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.PublicFolder\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.ThreeDObjects\fP, \fBJBToolkit\&.Windows\&.KnownFolder\&.Downloads\fP }"
.br
.RI "Standard folders registered with the system\&. These folders are installed with Windows Vista and later operating systems, and a computer will have only folders appropriate to it installed\&. "
.ti -1c
.RI "enum \fBJBToolkit\&.Windows\&.ContextType\fP { \fBJBToolkit\&.Windows\&.ContextType\&.Application\fP, \fBJBToolkit\&.Windows\&.ContextType\&.HttpContext\fP }"
.br
.RI "Specify application or website / web service context "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
