.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/WinForms/Helpers/DirtyTracker.cs" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/WinForms/Helpers/DirtyTracker.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.DirtyTrackerControlIgnoreList\fP"
.br
.RI "Put any control you don't want to be picked up by the dirty tracker here "
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.EventDrivenDirtyTracker\fP"
.br
.RI "Tracks control changes\&. Good if you want to be able to tell if something needs saving or not - It fires on the changing event of the control without taking into account the value of say a text box\&.\&.\&. Use the '\fBValueDrivenDirtyTracker\fP' instead to enable that option "
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ValueDrivenDirtyTracker\fP"
.br
.RI "Tracks control changes\&. Good if you want to be able to tell if something needs saving or not - It fires on the changing event while also taking into account the initial values (of say a text box) "
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ControlDirtyTracker\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.ControlDirtyTrackerCollection\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.WinForms\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
