.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/FuzzyLogic/Algorithms/DoubleMetaphoneAlgorithm.cs" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/FuzzyLogic/Algorithms/DoubleMetaphoneAlgorithm.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.FuzzyLogic\&.DoubleMetaphoneAlgorithm\fP"
.br
.RI "https://en.wikipedia.org/wiki/Metaphone 
.br

.br
 Get a 4 character 'soundex' - to compare 
.br

.br
 Metaphone is a phonetic algorithm, published by Lawrence Philips in 1990, for indexing words by their English pronunciation\&.[1] It fundamentally improves on the Soundex algorithm by using information about variations and inconsistencies in English spelling and pronunciation to produce a more accurate encoding, which does a better job of matching words and names which sound similar\&. 
.br

.br
 Origin: https://github.com/tylerjensen/FuzzyStrings "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.FuzzyLogic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
