.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Web/Email.cs" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Web/Email.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Web\&.Email\fP"
.br
.RI "Contains methods for validating and sending emails (validating being thing such as validating the attached file size or extention) "
.ti -1c
.RI "class \fBJBToolkit\&.Web\&.EmailResult\fP"
.br
.RI "Contains email sent status information "
.ti -1c
.RI "class \fBJBToolkit\&.Web\&.SuccessEmailResult\fP"
.br
.RI "Contains email sent 'success' information "
.ti -1c
.RI "class \fBJBToolkit\&.Web\&.FailureEmailResult\fP"
.br
.RI "Contains email sent 'success' information "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Web\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
