.TH "EventArgs" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.InterProcessComms\&.DataReceivedEventArgs\fP, and \fBJBToolkit\&.Streams\&.ThrottledStream\&.ThrottleStreamOutputEventArgs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
