.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Zip/ExtractOtherCompressedArchiveTypes.cs" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Zip/ExtractOtherCompressedArchiveTypes.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Zip\&.ExtractOtherCompressedArchiveTypes\fP"
.br
.RI "Extract other types of compressed archive file other than \&.zip\&. Support the follow file types: \&.zip, \&.7z, \&.tar, \&.gzip, \&.tar, \&.tar\&.gz, \&.gzip, \&.rar "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Zip\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
