.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/SharePoint/CSOM/Manage/FileInfo.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/SharePoint/CSOM/Manage/FileInfo.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.SharePoint\&.CSOM\&.Manage\fP"
.br
.RI "\fBSharePoint\fP file and folder management utilities using \fBCSOM\fP "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.SharePoint\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.SharePoint\&.CSOM\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
