.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Google/Geocoding.cs" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Google/Geocoding.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\fP"
.br
.RI "Perform geocoding operations on longitue and latitude or reverse-geocoding (i\&.e\&. long lat from address)\&. Can Get the full Google geocoding object or just the desired formatted address or lat long coordinates "
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\&.GoogleGeolocationObject\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\&.Result\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\&.Geometry\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\&.Location\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\&.Viewport\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\&.Northeast\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\&.Southwest\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.GoogeApi\&.Geocoding\&.Address_Components\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.GoogeApi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
