.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Imaging/HtmlImageHelper.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Imaging/HtmlImageHelper.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Images\&.ImageHelper\fP"
.br
.RI "Image manipulation helper methods "
.ti -1c
.RI "class \fBJBToolkit\&.Images\&.ImageHelper\&.HtmlImageHelper\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Images\&.ImageHelper\&.HtmlImageHelper\&.DataImage\fP"
.br
.RI "Parse base 64 to \fBDataImage\fP object consisting of raw byte[] data and the image and mime type\&. "
.ti -1c
.RI "class \fBJBToolkit\&.Images\&.ImageHelper\&.HtmlImageHelper\&.HtmlPath\fP"
.br
.RI "Paths to image in Html file along with a path type (i\&.e\&. local, relative, remote, data) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Images\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
