.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Imaging/IconImageHelper.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Imaging/IconImageHelper.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Images\&.ImageHelper\fP"
.br
.RI "Image manipulation helper methods "
.ti -1c
.RI "class \fBJBToolkit\&.Images\&.ImageHelper\&.IconHelper\fP"
.br
.RI "A Helper class for multi-resolution icon files "
.ti -1c
.RI "class \fBJBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\fP"
.br
.RI "Extension of the System\&.Drawing\&.Icon for getting header information and individsual icons from a multi-resolution icon "
.ti -1c
.RI "class \fBJBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\fP"
.br
.RI "Each icon if the file has its own header with information, stored in this object "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Images\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
