.TH "IDisposable" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDisposable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.Domain\&.Impersonation\&.Impersonator\fP, \fBJBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\fP, \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP, \fBJBToolkit\&.SafeStream\&.SafeFileStream\fP, \fBJBToolkit\&.Windows\&.ConsoleHelper\&.ProgressBar\fP, and \fBJBToolkit\&.Zip\&.Native\&.ZipArchive\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
