.TH "IList" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IList
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\fP, and \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
