.TH "IList" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IList
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionValueCollection\fP, and \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionValueCollection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
