.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Domain/Impersonation.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Domain/Impersonation.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Domain\&.Impersonation\&.Win32NativeMethods\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Domain\&.Impersonation\&.Impersonator\fP"
.br
.RI "Used to perform execution of code under an elivated permission context "
.ti -1c
.RI "class \fBJBToolkit\&.Domain\&.Impersonation\&.Impersonator\&.ImpersonatorCredentials\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Domain\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Domain\&.Impersonation\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJBToolkit\&.Domain\&.Impersonation\&.ServerType\fP { \fBJBToolkit\&.Domain\&.Impersonation\&.ServerType\&.DMZ\fP, \fBJBToolkit\&.Domain\&.Impersonation\&.ServerType\&.DOMAIN\fP }"
.br
.ti -1c
.RI "enum \fBJBToolkit\&.Domain\&.Impersonation\&.LogonType\fP { \fBJBToolkit\&.Domain\&.Impersonation\&.LogonType\&.LOGON32_LOGON_INTERACTIVE\fP = 2, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonType\&.LOGON32_LOGON_NETWORK\fP = 3, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonType\&.LOGON32_LOGON_BATCH\fP = 4, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonType\&.LOGON32_LOGON_SERVICE\fP = 5, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonType\&.LOGON32_LOGON_UNLOCK\fP = 7, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonType\&.LOGON32_LOGON_NETWORK_CLEARTEXT\fP = 8, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonType\&.LOGON32_LOGON_NEW_CREDENTIALS\fP = 9 }"
.br
.ti -1c
.RI "enum \fBJBToolkit\&.Domain\&.Impersonation\&.LogonProvider\fP { \fBJBToolkit\&.Domain\&.Impersonation\&.LogonProvider\&.LOGON32_PROVIDER_DEFAULT\fP = 0, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonProvider\&.LOGON32_PROVIDER_WINNT35\fP = 1, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonProvider\&.LOGON32_PROVIDER_WINNT40\fP = 2, \fBJBToolkit\&.Domain\&.Impersonation\&.LogonProvider\&.LOGON32_PROVIDER_WINNT50\fP = 3 }"
.br
.ti -1c
.RI "enum \fBJBToolkit\&.Domain\&.Impersonation\&.ImpersonationLevel\fP { \fBJBToolkit\&.Domain\&.Impersonation\&.ImpersonationLevel\&.SecurityAnonymous\fP = 0, \fBJBToolkit\&.Domain\&.Impersonation\&.ImpersonationLevel\&.SecurityIdentification\fP = 1, \fBJBToolkit\&.Domain\&.Impersonation\&.ImpersonationLevel\&.SecurityImpersonation\fP = 2, \fBJBToolkit\&.Domain\&.Impersonation\&.ImpersonationLevel\&.SecurityDelegation\fP = 3 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
