.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/FuzzyLogic/Algorithms/JaroWinklerDistance.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/FuzzyLogic/Algorithms/JaroWinklerDistance.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.FuzzyLogic\&.Algorithms\fP"
.br
.RI "Origin (before extension): https://github.com/kdjones/fuzzystring "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.FuzzyLogic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
