.TH "JBToolkit.Views.JQFRowHighlightStrip" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.JQFRowHighlightStrip
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBHighlightStripTypeEnum\fP { \fBHighlightStripTypeEnum\&.Success\fP, \fBHighlightStripTypeEnum\&.Warning\fP, \fBHighlightStripTypeEnum\&.Danger\fP, \fBHighlightStripTypeEnum\&.Info\fP, \fBHighlightStripTypeEnum\&.Primary\fP, \fBHighlightStripTypeEnum\&.Grey\fP, \fBHighlightStripTypeEnum\&.Custom\fP }"
.br
.RI "If using 'Custom' - be sure to set the CustomHighlight color, i\&.e\&. #3f80ea "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHighlightStripTypeEnum\fP \fBHighlightStripType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCustomHighlighColour\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBText\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBJBToolkit\&.Views\&.JQFRowHighlightStrip\&.HighlightStripTypeEnum\fP\fC [strong]\fP"

.PP
If using 'Custom' - be sure to set the CustomHighlight color, i\&.e\&. #3f80ea 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
.TP
\fB\fIWarning \fP\fP
.TP
\fB\fIDanger \fP\fP
.TP
\fB\fIInfo \fP\fP
.TP
\fB\fIPrimary \fP\fP
.TP
\fB\fIGrey \fP\fP
.TP
\fB\fICustom \fP\fP
.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Views\&.JQFRowHighlightStrip\&.CustomHighlighColour\fC [get]\fP, \fC [set]\fP"

.SS "\fBHighlightStripTypeEnum\fP JBToolkit\&.Views\&.JQFRowHighlightStrip\&.HighlightStripType\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQFRowHighlightStrip\&.Text\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
