.TH "JBToolkit.SharePoint.CSOM" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.SharePoint.CSOM
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBObjects\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAuthentication\fP"
.br
.RI "Authenticate with \fBSharePoint\fP using SCOM API "
.ti -1c
.RI "class \fBDownload\fP"
.br
.RI "\fBSharePoint\fP file and folder download utilities using SCOM "
.ti -1c
.RI "class \fBManage\fP"
.br
.RI "\fBSharePoint\fP file and folder management utilities using \fBCSOM\fP "
.ti -1c
.RI "class \fBUpload\fP"
.br
.RI "\fBSharePoint\fP file \fBUpload\fP utilities using SCOM "
.ti -1c
.RI "class \fBUtils\fP"
.br
.RI "\fBSharePoint\fP SCOM utility methods "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
