.TH "JBToolkit.Domain.ADUser" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Domain.ADUser \- Object to store user details, such as username, full name, email, job title etc and what roles and permissions they have\&. Also can get user profile image  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDisplayName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUsername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDomain\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUserAccount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBJobTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBOffice\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDepartment\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTelephone\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMobile\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFax\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIPPhone\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBEmail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBADUser\fP \fBManager\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< string > \fBMemberships\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object to store user details, such as username, full name, email, job title etc and what roles and permissions they have\&. Also can get user profile image 


.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Domain\&.ADUser\&.Department\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.DisplayName\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.Domain\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.Email\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.Fax\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.IPPhone\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.JobTitle\fC [get]\fP, \fC [set]\fP"

.SS "\fBADUser\fP JBToolkit\&.Domain\&.ADUser\&.Manager\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<string> JBToolkit\&.Domain\&.ADUser\&.Memberships\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.Mobile\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.Office\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.Telephone\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.UserAccount\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.ADUser\&.Username\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
