.TH "JBToolkit.Images.ColourHelper.ColourGenerator" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Images.ColourHelper.ColourGenerator \- Generates random colours close to primary colours as hex string and doesn't repeat a colour  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBNextColour\fP ()"
.br
.RI "Generate the next colour "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Color \fBGetRandomColour\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates random colours close to primary colours as hex string and doesn't repeat a colour 


.SH "Member Function Documentation"
.PP 
.SS "static Color JBToolkit\&.Images\&.ColourHelper\&.ColourGenerator\&.GetRandomColour ()\fC [static]\fP"

.SS "string JBToolkit\&.Images\&.ColourHelper\&.ColourGenerator\&.NextColour ()"

.PP
Generate the next colour 

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
