.TH "JBToolkit.Database.DBGeneric" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Database.DBGeneric
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDBConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDBGeneric\fP (string dbname, string connectionString)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Database\&.DBGeneric\&.DBGeneric (string dbname, string connectionString)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
