.TH "JBToolkit.Csv.Native" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Csv.Native
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCsvHelper\fP"
.br
.RI "Convert CSV from and to a DataTable\&. This class doesn't require any third party packages to use which can sometimes be useful, however it may not account for every single permutation of a CSV file, ony basic\&. This class does however support strings wrapped in 'Speachmarks' quite nicely, whic quite a lot of CSV to DataTable implementations don't seem to get right\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
