.TH "JBToolkit.Web.EmailResult" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Web.EmailResult \- Contains email sent status information  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.Web\&.FailureEmailResult\fP, and \fBJBToolkit\&.Web\&.SuccessEmailResult\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBSuccess\fP\fC [get, protected set]\fP"
.br
.ti -1c
.RI "string \fBMessage\fP\fC [get, protected set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains email sent status information 


.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Web\&.EmailResult\&.Message\fC [get]\fP, \fC [protected set]\fP"

.SS "bool JBToolkit\&.Web\&.EmailResult\&.Success\fC [get]\fP, \fC [protected set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
