.TH "JBToolkit.Streams.ThrottledStream.ThrottleStreamOutput" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Streams.ThrottledStream.ThrottleStreamOutput \- Object which can be passed into the constructor which stores the current 'bytes per second' and 'percentage complete'\&. Can also utilise the 'ThrottleStreamOutputEvent'  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBBytesPerSecond\fP = 0\&.0\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBPercentageComplete\fP = 0\&.0\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object which can be passed into the constructor which stores the current 'bytes per second' and 'percentage complete'\&. Can also utilise the 'ThrottleStreamOutputEvent' 


.SH "Property Documentation"
.PP 
.SS "double JBToolkit\&.Streams\&.ThrottledStream\&.ThrottleStreamOutput\&.BytesPerSecond = 0\&.0\fC [get]\fP, \fC [set]\fP"

.SS "double JBToolkit\&.Streams\&.ThrottledStream\&.ThrottleStreamOutput\&.PercentageComplete = 0\&.0\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
