.TH "JBToolkit.Database" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Database
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataTableState\fP"
.br
.ti -1c
.RI "class \fBDataTableStates\fP"
.br
.RI "For saving JQuery DataTable states (column order, column visibility, filters etc) - Saves in a provided DataBase\&. If the standard table doesn't exist this class will create it "
.ti -1c
.RI "class \fBDbConnection\fP"
.br
.RI "Abstract database provider class "
.ti -1c
.RI "class \fBDbGeneric\fP"
.br
.RI "Use to initialise the simplest DB class "
.ti -1c
.RI "class \fBDbResult\fP"
.br
.RI "Results object from a DB command "
.ti -1c
.RI "class \fBTreeViewCache\fP"
.br
.RI "For saving JSTree states (hierarchy, expanded nodes) - Saves in a provided DataBase\&. If the standard table doesn't exist this class will create it "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
