.TH "JBToolkit.ConsoleHelper.Options.HelpOption" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options.HelpOption
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.ConsoleHelper\&.Options\&.Option\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpOption\fP (\fBCommandSet\fP commands, \fBOption\fP d)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnParseComplete\fP (\fBOptionContext\fP c)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.ConsoleHelper\&.Options\&.HelpOption\&.HelpOption (\fBCommandSet\fP commands, \fBOption\fP d)"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.ConsoleHelper\&.Options\&.HelpOption\&.OnParseComplete (\fBOptionContext\fP c)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBJBToolkit\&.ConsoleHelper\&.Options\&.Option\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
