.TH "JBToolkit.InterProcessComms.MemoryMappedFiles.SharedMemoryClient" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.MemoryMappedFiles.SharedMemoryClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSharedMemoryClient\fP ()"
.br
.ti -1c
.RI "\fBSharedMemoryClient\fP (string mapFilename)"
.br
.ti -1c
.RI "void \fBSend\fP (string data)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryClient\&.SharedMemoryClient ()"

.SS "JBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryClient\&.SharedMemoryClient (string mapFilename)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryClient\&.Send (string data)"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
