.TH "JBToolkit.Domain" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Domain
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBImpersonation\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdAccessor\fP"
.br
.RI "Accesses a given Active Directory server as specified in the web\&.config for retrieving additional user information "
.ti -1c
.RI "class \fBAdUser\fP"
.br
.RI "Object to store user details, such as username, full name, email, job title etc and what roles and permissions they have\&. Also can get user profile image "
.ti -1c
.RI "class \fBDomainHelper\fP"
.br
.RI "\fBDomain\fP tools "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
