.TH "JBToolkit.Encryption" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Encryption
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnectionStringEncryptor\fP"
.br
.RI "Very simple connection string encryptor\&. Useful to hide the connection string from ordinary service and not have any invalid XML characters, while also being sharable or to be easily decrypted if needs be "
.ti -1c
.RI "class \fBStringEncrypt\fP"
.br
.RI "Decent method for encrypting and decrypting strings "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
