.TH "JBToolkit.Database.DbGeneric" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Database.DbGeneric \- Use to initialise the simplest DB class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.Database\&.DbConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDbGeneric\fP (string dbname, string connectionString, string applicationName)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Use to initialise the simplest DB class 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Database\&.DbGeneric\&.DbGeneric (string dbname, string connectionString, string applicationName)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
