.TH "JBToolkit.Web.SuccessEmailResult" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Web.SuccessEmailResult \- Contains email sent 'success' information  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.Web\&.EmailResult\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSuccessEmailResult\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Contains email sent 'success' information 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Web\&.SuccessEmailResult\&.SuccessEmailResult ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
