.TH "JBToolkit.AssemblyHelper.CultureHelper" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.AssemblyHelper.CultureHelper
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBGloballySetCultureToGB\fP ()"
.br
.RI "Used for 3rd party solution template, where the culture is set to US and so messes up DateTimes (i\&.e\&. M-Files) "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void JBToolkit\&.AssemblyHelper\&.CultureHelper\&.GloballySetCultureToGB ()\fC [static]\fP"

.PP
Used for 3rd party solution template, where the culture is set to US and so messes up DateTimes (i\&.e\&. M-Files) 

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
