.TH "JBToolkit.WinForms.ColorPickerColumn" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.ColorPickerColumn \- Column colour - to be used with the ColourPicker control  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDataGridViewColumn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorPickerColumn\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override DataGridViewCell \fBCellTemplate\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Column colour - to be used with the ColourPicker control 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.ColorPickerColumn\&.ColorPickerColumn ()"

.SH "Property Documentation"
.PP 
.SS "override DataGridViewCell JBToolkit\&.WinForms\&.ColorPickerColumn\&.CellTemplate\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
