.TH "JBToolkit.InterProcessComms.Sockets.SocketClient" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.Sockets.SocketClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSocketClient\fP ()"
.br
.ti -1c
.RI "\fBSocketClient\fP (int port)"
.br
.ti -1c
.RI "void \fBSend\fP (string data)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.Sockets\&.SocketClient\&.SocketClient ()"

.SS "JBToolkit\&.InterProcessComms\&.Sockets\&.SocketClient\&.SocketClient (int port)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.Sockets\&.SocketClient\&.Send (string data)"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
