.TH "JBToolkit.Views.IJqueryDataTable" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.IJqueryDataTable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.Views\&._JqueryDataTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGenerateFilters\fP ()"
.br
.ti -1c
.RI "string \fBGenerateRegisterDataTableScript\fP ()"
.br
.ti -1c
.RI "string \fBGenerateRegisterFiltersScript\fP ()"
.br
.ti -1c
.RI "string \fBGenerateAdditionalJavaScript\fP ()"
.br
.ti -1c
.RI "string \fBGenerateHtmlTable\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string JBToolkit\&.Views\&.IJqueryDataTable\&.GenerateAdditionalJavaScript ()"

.PP
Implemented in \fBJBToolkit\&.Views\&.JqueryEditorDataTable\fP, \fBJBToolkit\&.Views\&.JqueryAjaxDataTable\fP, \fBJBToolkit\&.Views\&.JqueryJsonDataTable\fP, \fBJBToolkit\&.Views\&.JqueryHtmlDataTable\fP, and \fBJBToolkit\&.Views\&._JqueryDataTable\fP\&.
.SS "string JBToolkit\&.Views\&.IJqueryDataTable\&.GenerateFilters ()"

.PP
Implemented in \fBJBToolkit\&.Views\&.JqueryEditorDataTable\fP, \fBJBToolkit\&.Views\&.JqueryAjaxDataTable\fP, \fBJBToolkit\&.Views\&.JqueryJsonDataTable\fP, \fBJBToolkit\&.Views\&.JqueryHtmlDataTable\fP, and \fBJBToolkit\&.Views\&._JqueryDataTable\fP\&.
.SS "string JBToolkit\&.Views\&.IJqueryDataTable\&.GenerateHtmlTable ()"

.PP
Implemented in \fBJBToolkit\&.Views\&.JqueryHtmlDataTable\fP, \fBJBToolkit\&.Views\&.JqueryEditorDataTable\fP, \fBJBToolkit\&.Views\&.JqueryAjaxDataTable\fP, \fBJBToolkit\&.Views\&.JqueryJsonDataTable\fP, and \fBJBToolkit\&.Views\&._JqueryDataTable\fP\&.
.SS "string JBToolkit\&.Views\&.IJqueryDataTable\&.GenerateRegisterDataTableScript ()"

.PP
Implemented in \fBJBToolkit\&.Views\&.JqueryEditorDataTable\fP, \fBJBToolkit\&.Views\&.JqueryAjaxDataTable\fP, \fBJBToolkit\&.Views\&.JqueryHtmlDataTable\fP, \fBJBToolkit\&.Views\&.JqueryJsonDataTable\fP, and \fBJBToolkit\&.Views\&._JqueryDataTable\fP\&.
.SS "string JBToolkit\&.Views\&.IJqueryDataTable\&.GenerateRegisterFiltersScript ()"

.PP
Implemented in \fBJBToolkit\&.Views\&.JqueryEditorDataTable\fP, \fBJBToolkit\&.Views\&.JqueryAjaxDataTable\fP, \fBJBToolkit\&.Views\&.JqueryJsonDataTable\fP, \fBJBToolkit\&.Views\&.JqueryHtmlDataTable\fP, and \fBJBToolkit\&.Views\&._JqueryDataTable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
