.TH "JBToolkit.Database.DataTableStates" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Database.DataTableStates \- For saving JQuery DataTable states (column order, column visibility, filters etc) - Saves in a provided DataBase\&. If the standard table doesn't exist this class will create it  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataTableStates\fP (string dbName, string connectionString)"
.br
.ti -1c
.RI "string \fBGetTableState\fP (string tableId)"
.br
.ti -1c
.RI "bool \fBUpdateTableState\fP (string tableId, string tableSettings)"
.br
.in -1c
.SH "Detailed Description"
.PP 
For saving JQuery DataTable states (column order, column visibility, filters etc) - Saves in a provided DataBase\&. If the standard table doesn't exist this class will create it 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Database\&.DataTableStates\&.DataTableStates (string dbName, string connectionString)"

.SH "Member Function Documentation"
.PP 
.SS "string JBToolkit\&.Database\&.DataTableStates\&.GetTableState (string tableId)"

.SS "bool JBToolkit\&.Database\&.DataTableStates\&.UpdateTableState (string tableId, string tableSettings)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
