.TH "JBToolkit.Csv.Native.CsvHelper" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Csv.Native.CsvHelper \- Convert CSV from and to a DataTable\&. This class doesn't require any third party packages to use which can sometimes be useful, however it may not account for every single permutation of a CSV file, ony basic\&. This class does however support strings wrapped in 'Speachmarks' quite nicely, whic quite a lot of CSV to DataTable implementations don't seem to get right\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDataTable\fP \fBCsvToDataTable\fP (string csvPath, char delimeter=',')"
.br
.RI "Convert CSV from a DataTable\&. This class doesn't require any third party packages to use which can sometimes be useful, however it may not account for every single permutation of a CSV file, ony basic\&. This class does however support strings wrapped in 'Speachmarks' quite nicely, whic quite a lot of CSV to DataTable implementations don't seem to get right\&. "
.ti -1c
.RI "static void \fBToCsvFile\fP (\fBDataTable\fP dataTable, string path, char seperator=',')"
.br
.RI "Convert CSV from and to a DataTable\&. It will wrapp all fields with speachmarks for simplicity, which is highly compatible, however If you have a different implementation of CSV reader that type casts you may struggle\&. "
.in -1c
.SH "Detailed Description"
.PP 
Convert CSV from and to a DataTable\&. This class doesn't require any third party packages to use which can sometimes be useful, however it may not account for every single permutation of a CSV file, ony basic\&. This class does however support strings wrapped in 'Speachmarks' quite nicely, whic quite a lot of CSV to DataTable implementations don't seem to get right\&. 


.SH "Member Function Documentation"
.PP 
.SS "static \fBDataTable\fP JBToolkit\&.Csv\&.Native\&.CsvHelper\&.CsvToDataTable (string csvPath, char delimeter = \fC','\fP)\fC [static]\fP"

.PP
Convert CSV from a DataTable\&. This class doesn't require any third party packages to use which can sometimes be useful, however it may not account for every single permutation of a CSV file, ony basic\&. This class does however support strings wrapped in 'Speachmarks' quite nicely, whic quite a lot of CSV to DataTable implementations don't seem to get right\&. 
.SS "static void JBToolkit\&.Csv\&.Native\&.CsvHelper\&.ToCsvFile (\fBDataTable\fP dataTable, string path, char seperator = \fC','\fP)\fC [static]\fP"

.PP
Convert CSV from and to a DataTable\&. It will wrapp all fields with speachmarks for simplicity, which is highly compatible, however If you have a different implementation of CSV reader that type casts you may struggle\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
