.TH "JBToolkit.PdfDoc.PdfOutput" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.PdfDoc.PdfOutput
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBOutputFilePath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "MemoryStream \fBOutputStream\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Action< \fBPdfConvertDocument\fP, byte[]> \fBOutputCallback\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "Action<\fBPdfConvertDocument\fP, byte[]> JBToolkit\&.PdfDoc\&.PdfOutput\&.OutputCallback\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfOutput\&.OutputFilePath\fC [get]\fP, \fC [set]\fP"

.SS "MemoryStream JBToolkit\&.PdfDoc\&.PdfOutput\&.OutputStream\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
