.TH "JBToolkit.InterProcessComms.MessageQueues.MessageQueueServer" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.MessageQueues.MessageQueueServer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageQueueServer\fP ()"
.br
.ti -1c
.RI "\fBMessageQueueServer\fP (string queueName)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBDataReceivedEventArgs\fP > \fBReceived\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueServer\&.MessageQueueServer ()"

.SS "JBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueServer\&.MessageQueueServer (string queueName)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueServer\&.Start ()"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SS "void JBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueServer\&.Stop ()"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBDataReceivedEventArgs\fP> JBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueServer\&.Received"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
