.TH "JBToolkit.XmlDoc.MailMerge" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.XmlDoc.MailMerge
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOpenXmlMailMerge\fP"
.br
.RI "Uses OpenXML to perform a Word Mail Merge\&. "
.ti -1c
.RI "class \fBReAlMailMerge\fP"
.br
.RI "Mail merging using a 3rd party command line tool\&. "
.ti -1c
.RI "class \fBWordInteropMailMerge\fP"
.br
.RI "Uses OpenXML to perform a Word Mail Merge\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
