.TH "JBToolkit.ConsoleHelper.Options.Command" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options.Command
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.ConsoleHelper\&.Options\&.HelpCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommand\fP (string name, string help=null)"
.br
.ti -1c
.RI "virtual int \fBInvoke\fP (\fBIEnumerable\fP< string > arguments)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBHelp\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBOptionSet\fP \fBOptions\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Action< \fBIEnumerable\fP< string > > \fBRun\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCommandSet\fP \fBCommandSet\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.ConsoleHelper\&.Options\&.Command\&.Command (string name, string help = \fCnull\fP)"

.SH "Member Function Documentation"
.PP 
.SS "virtual int JBToolkit\&.ConsoleHelper\&.Options\&.Command\&.Invoke (\fBIEnumerable\fP< string > arguments)\fC [virtual]\fP"

.PP
Reimplemented in \fBJBToolkit\&.ConsoleHelper\&.Options\&.HelpCommand\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBCommandSet\fP JBToolkit\&.ConsoleHelper\&.Options\&.Command\&.CommandSet\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.ConsoleHelper\&.Options\&.Command\&.Help\fC [get]\fP"

.SS "string JBToolkit\&.ConsoleHelper\&.Options\&.Command\&.Name\fC [get]\fP"

.SS "\fBOptionSet\fP JBToolkit\&.ConsoleHelper\&.Options\&.Command\&.Options\fC [get]\fP, \fC [set]\fP"

.SS "Action<\fBIEnumerable\fP<string> > JBToolkit\&.ConsoleHelper\&.Options\&.Command\&.Run\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
