.TH "JBToolkit.Extensions.SourceCode.SourceCodeFormatter.LenientJsonFormatter.StringWalker" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Extensions.SourceCode.SourceCodeFormatter.LenientJsonFormatter.StringWalker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringWalker\fP (string s)"
.br
.ti -1c
.RI "bool \fBMoveNext\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBIndex\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsEscaped\fP\fC [get]\fP"
.br
.ti -1c
.RI "char \fBCurrentChar\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.StringWalker\&.StringWalker (string s)"

.SH "Member Function Documentation"
.PP 
.SS "bool JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.StringWalker\&.MoveNext ()"

.SH "Property Documentation"
.PP 
.SS "char JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.StringWalker\&.CurrentChar\fC [get]\fP"

.SS "int JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.StringWalker\&.Index\fC [get]\fP"

.SS "bool JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.StringWalker\&.IsEscaped\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
