.TH "JBToolkit.InterProcessComms.Sockets.SocketServer" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.Sockets.SocketServer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSocketServer\fP ()"
.br
.ti -1c
.RI "\fBSocketServer\fP (int port)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBDataReceivedEventArgs\fP > \fBReceived\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.Sockets\&.SocketServer\&.SocketServer ()"

.SS "JBToolkit\&.InterProcessComms\&.Sockets\&.SocketServer\&.SocketServer (int port)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.Sockets\&.SocketServer\&.Start ()"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SS "void JBToolkit\&.InterProcessComms\&.Sockets\&.SocketServer\&.Stop ()"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBDataReceivedEventArgs\fP> JBToolkit\&.InterProcessComms\&.Sockets\&.SocketServer\&.Received"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
