.TH "JBToolkit.Views.Parameters" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.Parameters
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameters\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdraw\fP"
.br
.ti -1c
.RI "\fBDataTableColumn\fP[] \fBcolumns\fP"
.br
.ti -1c
.RI "\fBDataTableOrder\fP[] \fBorder\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "\fBDataTableSearch\fP \fBsearch\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Views\&.Parameters\&.Parameters ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBDataTableColumn\fP [] JBToolkit\&.Views\&.Parameters\&.columns"

.SS "int JBToolkit\&.Views\&.Parameters\&.draw"

.SS "int JBToolkit\&.Views\&.Parameters\&.length"

.SS "\fBDataTableOrder\fP [] JBToolkit\&.Views\&.Parameters\&.order"

.SS "\fBDataTableSearch\fP JBToolkit\&.Views\&.Parameters\&.search"

.SS "int JBToolkit\&.Views\&.Parameters\&.start"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
