.TH "JBToolkit.Zip.Native" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Zip.Native
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZipArchive\fP"
.br
.RI "Read, write and modify \fBZip\fP files using the \fBZip\fP implementation native to \fBWindows\fP\&. It doesn't require any third party packages to utilise which can be benefifical in some circumstances\&. It may struggle with large zip files however\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
