.TH "JBToolkit.ConsoleHelper.Options.CommandOption" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options.CommandOption
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.ConsoleHelper\&.Options\&.Option\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandOption\fP (\fBCommand\fP command, string commandName=null, bool hidden=false)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnParseComplete\fP (\fBOptionContext\fP c)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCommand\fP \fBCommand\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBCommandName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.ConsoleHelper\&.Options\&.CommandOption\&.CommandOption (\fBCommand\fP command, string commandName = \fCnull\fP, bool hidden = \fCfalse\fP)"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.ConsoleHelper\&.Options\&.CommandOption\&.OnParseComplete (\fBOptionContext\fP c)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBJBToolkit\&.ConsoleHelper\&.Options\&.Option\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBCommand\fP JBToolkit\&.ConsoleHelper\&.Options\&.CommandOption\&.Command\fC [get]\fP"

.SS "string JBToolkit\&.ConsoleHelper\&.Options\&.CommandOption\&.CommandName\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
