.TH "JBToolkit.AssemblyHelper" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.AssemblyHelper
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCultureHelper\fP"
.br
.ti -1c
.RI "class \fBEmbeddedResourceHelper\fP"
.br
.RI "Methods for extracting and utilising resources embedded in the DLL (including assemblies and command line utilities) "
.ti -1c
.RI "class \fBVersionHelper\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
