.TH "JBToolkit.Views.JQFButton" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.JQFButton
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBButtonTargetEnum\fP { \fBButtonTargetEnum\&.Blank\fP, \fBButtonTargetEnum\&.Self\fP, \fBButtonTargetEnum\&.Top\fP, \fBButtonTargetEnum\&.Parent\fP }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBButtonTargetEnum\fP \fBTarget\fP = \fBButtonTargetEnum\&.Self\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBButtonClass\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIconClass\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBJBToolkit\&.Views\&.JQFButton\&.ButtonTargetEnum\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBlank \fP\fP
.TP
\fB\fISelf \fP\fP
.TP
\fB\fITop \fP\fP
.TP
\fB\fIParent \fP\fP
.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Views\&.JQFButton\&.ButtonClass\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQFButton\&.IconClass\fC [get]\fP, \fC [set]\fP"

.SS "\fBButtonTargetEnum\fP JBToolkit\&.Views\&.JQFButton\&.Target = \fBButtonTargetEnum\&.Self\fP\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQFButton\&.Text\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQFButton\&.Url\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
