.TH "JBToolkit.Views" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_JqueryDataTable\fP"
.br
.RI "Generates JQquery DataTable HTML from a Model "
.ti -1c
.RI "class \fBDataTableColumn\fP"
.br
.ti -1c
.RI "class \fBDataTableOrder\fP"
.br
.ti -1c
.RI "class \fBDataTableParameters\fP"
.br
.RI "Turns the Ajax call parameters into a DataTableParameter object "
.ti -1c
.RI "class \fBDataTableResultError\fP"
.br
.ti -1c
.RI "class \fBDataTableResultSet\fP"
.br
.RI "Data returned to DataTable "
.ti -1c
.RI "class \fBDataTableSearch\fP"
.br
.ti -1c
.RI "interface \fBIJqueryDataTable\fP"
.br
.ti -1c
.RI "class \fBJQFButton\fP"
.br
.ti -1c
.RI "class \fBJQFRow\fP"
.br
.ti -1c
.RI "class \fBJQFRowHighlightStrip\fP"
.br
.ti -1c
.RI "class \fBJQTColumn\fP"
.br
.RI "Individual column object "
.ti -1c
.RI "class \fBJQTHeader\fP"
.br
.RI "Header information "
.ti -1c
.RI "class \fBJQTRow\fP"
.br
.RI "\fBList\fP of columns "
.ti -1c
.RI "class \fBJQTSelectableDataSource\fP"
.br
.RI "You'll have to handle the javascript in the parent view, via creating an event handler referencing the given UniqueID "
.ti -1c
.RI "class \fBJQTSelectableDataSourceItem\fP"
.br
.RI "Iteams for SelectableDataSource "
.ti -1c
.RI "class \fBJQTSorting\fP"
.br
.RI "Sort direction and column index object "
.ti -1c
.RI "class \fBJqueryAjaxDataTable\fP"
.br
.RI "Optional Sever-side processing: Generates JQuery DataTable HTML from a Model, using data from ajax calls for server-side processing\&. "
.ti -1c
.RI "class \fBJqueryEditorDataTable\fP"
.br
.RI "Editable DataTable: Generates JQquery DataTable HTML from a Model that you can edit fields for\&. "
.ti -1c
.RI "class \fBJqueryFeed\fP"
.br
.RI "Generates JQquery Feed HTML from a Model "
.ti -1c
.RI "class \fBJqueryHtmlDataTable\fP"
.br
.RI "Generates JQquery DataTable HTML from a model\&. "
.ti -1c
.RI "class \fBJqueryJsonDataTable\fP"
.br
.RI "Generates JQuery DataTable HTML from a Model\&. "
.ti -1c
.RI "class \fBParameters\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHyperlinkTargetEnum\fP { \fBHyperlinkTargetEnum\&._blank\fP, \fBHyperlinkTargetEnum\&._self\fP, \fBHyperlinkTargetEnum\&._parent\fP, \fBHyperlinkTargetEnum\&._top\fP }"
.br
.RI "How to open a hyperlink "
.ti -1c
.RI "enum \fBJQTSortDirection\fP { \fBJQTSortDirection\&.ASCENDING\fP = 0, \fBJQTSortDirection\&.DECENDING\fP = 1 }"
.br
.RI "Column Sort Direction enum "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBJBToolkit\&.Views\&.HyperlinkTargetEnum\fP\fC [strong]\fP"

.PP
How to open a hyperlink 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fI_blank \fP\fP
.TP
\fB\fI_self \fP\fP
.TP
\fB\fI_parent \fP\fP
.TP
\fB\fI_top \fP\fP
.SS "enum \fBJBToolkit\&.Views\&.JQTSortDirection\fP\fC [strong]\fP"

.PP
Column Sort Direction enum 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIASCENDING \fP\fP
.TP
\fB\fIDECENDING \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
