.TH "JBToolkit.Streams.ThrottledStream.ThrottleStreamOutputEventArgs" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Streams.ThrottledStream.ThrottleStreamOutputEventArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThrottleStreamOutputEventArgs\fP (double bytesPerSecond, double percentageComplete)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBBytesPerSecond\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBPercentgeComplete\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Streams\&.ThrottledStream\&.ThrottleStreamOutputEventArgs\&.ThrottleStreamOutputEventArgs (double bytesPerSecond, double percentageComplete)"

.SH "Property Documentation"
.PP 
.SS "double JBToolkit\&.Streams\&.ThrottledStream\&.ThrottleStreamOutputEventArgs\&.BytesPerSecond\fC [get]\fP"

.SS "double JBToolkit\&.Streams\&.ThrottledStream\&.ThrottleStreamOutputEventArgs\&.PercentgeComplete\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
