.TH "JBToolkit.FuzzyLogic.Algorithms.BestFuzzyMatch" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.FuzzyLogic.Algorithms.BestFuzzyMatch
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.FuzzyLogic\&.Algorithms\&.BestDetailedFuzzyMatch\fP, and \fBJBToolkit\&.FuzzyLogic\&.Algorithms\&.QuickFuzzyMatch\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBIndex\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMatchText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSource\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBComparisonResultAverage\fP = 999\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBError\fP = string\&.Empty\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "double JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestFuzzyMatch\&.ComparisonResultAverage = 999\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestFuzzyMatch\&.Error = string\&.Empty\fC [get]\fP, \fC [set]\fP"

.SS "int JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestFuzzyMatch\&.Index\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestFuzzyMatch\&.MatchText\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestFuzzyMatch\&.Source\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
