.TH "JBToolkit.Windows.CommonFileTypeExtensions.MicrosoftOffice" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Windows.CommonFileTypeExtensions.MicrosoftOffice
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "static string[] \fBWord\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBExcel\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBPowerPoint\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBAccess\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBVisio\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBProject\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBPublisher\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBOutlook\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBXPS\fP\fC [get]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.Access\fC [static]\fP, \fC [get]\fP"

.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.Excel\fC [static]\fP, \fC [get]\fP"

.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.Outlook\fC [static]\fP, \fC [get]\fP"

.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.PowerPoint\fC [static]\fP, \fC [get]\fP"

.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.Project\fC [static]\fP, \fC [get]\fP"

.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.Publisher\fC [static]\fP, \fC [get]\fP"

.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.Visio\fC [static]\fP, \fC [get]\fP"

.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.Word\fC [static]\fP, \fC [get]\fP"

.SS "string [] JBToolkit\&.Windows\&.CommonFileTypeExtensions\&.MicrosoftOffice\&.XPS\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
