.TH "JBToolkit.Views.JQTRow" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.JQTRow \- \fBList\fP of columns  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBList\fP< \fBJQTColumn\fP > \fBColumns\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBList\fP of columns 


.SH "Property Documentation"
.PP 
.SS "\fBList\fP<\fBJQTColumn\fP> JBToolkit\&.Views\&.JQTRow\&.Columns\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
