.TH "JBToolkit.Images.ImageHelper.IconHelper.Icon.IconEntry" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Images.ImageHelper.IconHelper.Icon.IconEntry \- Each icon if the file has its own header with information, stored in this object  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIconEntry\fP (MemoryStream icoStream)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBWidth\fP"
.br
.ti -1c
.RI "byte \fBHeight\fP"
.br
.ti -1c
.RI "byte \fBColorCount\fP"
.br
.ti -1c
.RI "byte \fBReserved\fP"
.br
.ti -1c
.RI "short \fBPlanes\fP"
.br
.ti -1c
.RI "short \fBBitCount\fP"
.br
.ti -1c
.RI "int \fBBytesInRes\fP"
.br
.ti -1c
.RI "int \fBImageOffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Each icon if the file has its own header with information, stored in this object 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.IconEntry (MemoryStream icoStream)"

.SH "Member Data Documentation"
.PP 
.SS "short JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.BitCount"

.SS "int JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.BytesInRes"

.SS "byte JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.ColorCount"

.SS "byte JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.Height"

.SS "int JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.ImageOffset"

.SS "short JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.Planes"

.SS "byte JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.Reserved"

.SS "byte JBToolkit\&.Images\&.ImageHelper\&.IconHelper\&.Icon\&.IconEntry\&.Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
