.TH "JBToolkit.InterProcessComms.Wcf" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.Wcf \- It is binary;  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWcfClient\fP"
.br
.RI "Client to host communication (1 direction) Named Pipe implementation\&. "
.ti -1c
.RI "class \fBWcfServer\fP"
.br
.RI "Client to host communication (1 direction) Named Pipe implementation\&. "
.in -1c
.SH "Detailed Description"
.PP 
It is binary; 

Gist from: https://weblogs.asp.net/ricardoperes/local-machine-interprocess-communication-with-net
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
