.TH "JBToolkit.FuzzyLogic.Algorithms.BestDetailedFuzzyMatch" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.FuzzyLogic.Algorithms.BestDetailedFuzzyMatch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.FuzzyLogic\&.Algorithms\&.BestFuzzyMatch\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBWeakMatch\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBNormalMatch\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBStrongMatch\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< \fBFuzzyMatch\fP > \fBOrderedMatches\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBMultipleBestMatchesFound\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "bool JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestDetailedFuzzyMatch\&.MultipleBestMatchesFound\fC [get]\fP, \fC [set]\fP"

.SS "bool JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestDetailedFuzzyMatch\&.NormalMatch\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<\fBFuzzyMatch\fP> JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestDetailedFuzzyMatch\&.OrderedMatches\fC [get]\fP, \fC [set]\fP"

.SS "bool JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestDetailedFuzzyMatch\&.StrongMatch\fC [get]\fP, \fC [set]\fP"

.SS "bool JBToolkit\&.FuzzyLogic\&.Algorithms\&.BestDetailedFuzzyMatch\&.WeakMatch\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
