.TH "JBToolkit.PdfDoc.PdfConverter.HtmlToPdfConverter.PdfConvertTimeoutException" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.PdfDoc.PdfConverter.HtmlToPdfConverter.PdfConvertTimeoutException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.PdfDoc\&.PdfConverter\&.HtmlToPdfConverter\&.PdfConvertException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPdfConvertTimeoutException\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPdfConvertTimeoutException\fP (SerializationInfo serializationInfo, StreamingContext streamingContext)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.PdfDoc\&.PdfConverter\&.HtmlToPdfConverter\&.PdfConvertTimeoutException\&.PdfConvertTimeoutException ()"

.SS "JBToolkit\&.PdfDoc\&.PdfConverter\&.HtmlToPdfConverter\&.PdfConvertTimeoutException\&.PdfConvertTimeoutException (SerializationInfo serializationInfo, StreamingContext streamingContext)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
