.TH "JBToolkit.InterProcessComms.IIpcServer" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.IIpcServer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIDisposable\fP\&.
.PP
Inherited by \fBJBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\fP, \fBJBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueServer\fP, \fBJBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeServer\fP, \fBJBToolkit\&.InterProcessComms\&.NetRemoting\&.RemotingServer\fP, \fBJBToolkit\&.InterProcessComms\&.Sockets\&.SocketServer\fP, \fBJBToolkit\&.InterProcessComms\&.Wcf\&.WcfServer\fP, and \fBJBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.CopyDataServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBDataReceivedEventArgs\fP > \fBReceived\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.IIpcServer\&.Start ()"

.PP
Implemented in \fBJBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.CopyDataServer\fP, \fBJBToolkit\&.InterProcessComms\&.Wcf\&.WcfServer\fP, \fBJBToolkit\&.InterProcessComms\&.NetRemoting\&.RemotingServer\fP, \fBJBToolkit\&.InterProcessComms\&.Sockets\&.SocketServer\fP, \fBJBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueServer\fP, \fBJBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeServer\fP, and \fBJBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\fP\&.
.SS "void JBToolkit\&.InterProcessComms\&.IIpcServer\&.Stop ()"

.PP
Implemented in \fBJBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.CopyDataServer\fP, \fBJBToolkit\&.InterProcessComms\&.NetRemoting\&.RemotingServer\fP, \fBJBToolkit\&.InterProcessComms\&.Wcf\&.WcfServer\fP, \fBJBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueServer\fP, \fBJBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\fP, \fBJBToolkit\&.InterProcessComms\&.Sockets\&.SocketServer\fP, and \fBJBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeServer\fP\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBDataReceivedEventArgs\fP> JBToolkit\&.InterProcessComms\&.IIpcServer\&.Received"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
