.TH "JBToolkit.InterProcessComms.MessageQueues.MessageQueueClient" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.MessageQueues.MessageQueueClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageQueueClient\fP ()"
.br
.ti -1c
.RI "\fBMessageQueueClient\fP (string queueName)"
.br
.ti -1c
.RI "void \fBSend\fP (string data)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueClient\&.MessageQueueClient ()"

.SS "JBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueClient\&.MessageQueueClient (string queueName)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueClient\&.Send (string data)"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
