.TH "JBToolkit.ConsoleHelper.Options.CommandOptionSet" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options.CommandOptionSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionSet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandOptionSet\fP (\fBCommandSet\fP commands, \fBMessageLocalizerConverter\fP localizer)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBSetItem\fP (int index, \fBOption\fP item)"
.br
.ti -1c
.RI "override void \fBInsertItem\fP (int index, \fBOption\fP item)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.ConsoleHelper\&.Options\&.CommandOptionSet\&.CommandOptionSet (\fBCommandSet\fP commands, \fBMessageLocalizerConverter\fP localizer)"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.ConsoleHelper\&.Options\&.CommandOptionSet\&.InsertItem (int index, \fBOption\fP item)\fC [protected]\fP"

.SS "override void JBToolkit\&.ConsoleHelper\&.Options\&.CommandOptionSet\&.SetItem (int index, \fBOption\fP item)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
