.TH "JBToolkit.GoogeApi.Geocoding.Address_Components" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.GoogeApi.Geocoding.Address_Components
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBlong_name\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBshort_name\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string[] \fBtypes\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.GoogeApi\&.Geocoding\&.Address_Components\&.long_name\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.GoogeApi\&.Geocoding\&.Address_Components\&.short_name\fC [get]\fP, \fC [set]\fP"

.SS "string [] JBToolkit\&.GoogeApi\&.Geocoding\&.Address_Components\&.types\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
