.TH "JBToolkit.GoogeApi.Geocoding.Viewport" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.GoogeApi.Geocoding.Viewport
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBNortheast\fP \fBnortheast\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSouthwest\fP \fBsouthwest\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBNortheast\fP JBToolkit\&.GoogeApi\&.Geocoding\&.Viewport\&.northeast\fC [get]\fP, \fC [set]\fP"

.SS "\fBSouthwest\fP JBToolkit\&.GoogeApi\&.Geocoding\&.Viewport\&.southwest\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
