.TH "JBToolkit.Web.Url" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Web.Url
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBCombine\fP (string baseUrl, string method)"
.br
.RI "Similar to 'Path\&.Combine' but for URLs "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static string JBToolkit\&.Web\&.Url\&.Combine (string baseUrl, string method)\fC [static]\fP"

.PP
Similar to 'Path\&.Combine' but for URLs 
.PP
\fBParameters\fP
.RS 4
\fIbaseUrl\fP Parent URL
.br
\fImethod\fP MEthod URL
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
