.TH "JBToolkit.XmlDoc.Converters.WordToHtml" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.XmlDoc.Converters.WordToHtml \- Converts a Word \&.docx document to HTML  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSaveDocxToHtml\fP (string docxPath, string outputPath)"
.br
.ti -1c
.RI "static MemoryStream \fBConvertDocxToHtml\fP (string docxPath)"
.br
.ti -1c
.RI "static string \fBParseDOCX\fP (FileInfo fileInfo)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts a Word \&.docx document to HTML 


.SH "Member Function Documentation"
.PP 
.SS "static MemoryStream JBToolkit\&.XmlDoc\&.Converters\&.WordToHtml\&.ConvertDocxToHtml (string docxPath)\fC [static]\fP"

.SS "static string JBToolkit\&.XmlDoc\&.Converters\&.WordToHtml\&.ParseDOCX (FileInfo fileInfo)\fC [static]\fP"

.SS "static void JBToolkit\&.XmlDoc\&.Converters\&.WordToHtml\&.SaveDocxToHtml (string docxPath, string outputPath)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
