.TH "JBToolkit.ConsoleHelper.ConsoleSpinner" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.ConsoleSpinner \- Console wait or progress spinner and methods for manipulating the spinner  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsoleSpinner\fP ()"
.br
.ti -1c
.RI "void \fBUpdateProgress\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShowSpinner\fP ()"
.br
.RI "Show / start the spinner "
.ti -1c
.RI "static void \fBStopSpinner\fP ()"
.br
.RI "Stop / hide the spinner "
.in -1c
.SH "Detailed Description"
.PP 
Console wait or progress spinner and methods for manipulating the spinner 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.ConsoleHelper\&.ConsoleSpinner\&.ConsoleSpinner ()"

.SH "Member Function Documentation"
.PP 
.SS "static void JBToolkit\&.ConsoleHelper\&.ConsoleSpinner\&.ShowSpinner ()\fC [static]\fP"

.PP
Show / start the spinner 
.SS "static void JBToolkit\&.ConsoleHelper\&.ConsoleSpinner\&.StopSpinner ()\fC [static]\fP"

.PP
Stop / hide the spinner 
.SS "void JBToolkit\&.ConsoleHelper\&.ConsoleSpinner\&.UpdateProgress ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
