.TH "JBToolkit.InterProcessComms.NetRemoting.RemotingClient" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.NetRemoting.RemotingClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSend\fP (string data)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.NetRemoting\&.RemotingClient\&.Send (string data)"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
