.TH "JBToolkit.InterProcessComms.NetRemoting.RemoteObject" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.NetRemoting.RemoteObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMarshalByRefObject\fP, and \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemoteObject\fP ()"
.br
.ti -1c
.RI "\fBRemoteObject\fP (\fBIIpcClient\fP svc)"
.br
.ti -1c
.RI "override object \fBInitializeLifetimeService\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.NetRemoting\&.RemoteObject\&.RemoteObject ()"

.SS "JBToolkit\&.InterProcessComms\&.NetRemoting\&.RemoteObject\&.RemoteObject (\fBIIpcClient\fP svc)"

.SH "Member Function Documentation"
.PP 
.SS "override object JBToolkit\&.InterProcessComms\&.NetRemoting\&.RemoteObject\&.InitializeLifetimeService ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
