.TH "JBToolkit.Views.JQTColumn" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.JQTColumn \- Individual column object  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCssClass\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCssStyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSortableColumnText\fP = string\&.Empty\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSearchableColumnText\fP = string\&.Empty\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBColumnText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHyperlinkUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBHyperlinkTargetEnum\fP \fBHyperlinkTarget\fP = \fBHyperlinkTargetEnum\&._self\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Individual column object 


.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Views\&.JQTColumn\&.ColumnText\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQTColumn\&.CssClass\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQTColumn\&.CssStyle\fC [get]\fP, \fC [set]\fP"

.SS "\fBHyperlinkTargetEnum\fP JBToolkit\&.Views\&.JQTColumn\&.HyperlinkTarget = \fBHyperlinkTargetEnum\&._self\fP\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQTColumn\&.HyperlinkUrl\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQTColumn\&.SearchableColumnText = string\&.Empty\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQTColumn\&.SortableColumnText = string\&.Empty\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
