.TH "JBToolkit.WinForms.ValueDrivenDirtyTracker" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.ValueDrivenDirtyTracker \- Tracks control changes\&. Good if you want to be able to tell if something needs saving or not - It fires on the changing event while also taking into account the initial values (of say a text box)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBList\fP< \fBControl\fP > \fBGetListOfDirtyControls\fP ()"
.br
.ti -1c
.RI "void \fBSetAsClean\fP ()"
.br
.ti -1c
.RI "\fBValueDrivenDirtyTracker\fP (\fBForm\fP frm)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsDirty\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tracks control changes\&. Good if you want to be able to tell if something needs saving or not - It fires on the changing event while also taking into account the initial values (of say a text box) 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.ValueDrivenDirtyTracker\&.ValueDrivenDirtyTracker (\fBForm\fP frm)"

.SH "Member Function Documentation"
.PP 
.SS "\fBList\fP<\fBControl\fP> JBToolkit\&.WinForms\&.ValueDrivenDirtyTracker\&.GetListOfDirtyControls ()"

.SS "void JBToolkit\&.WinForms\&.ValueDrivenDirtyTracker\&.SetAsClean ()"

.SH "Property Documentation"
.PP 
.SS "bool JBToolkit\&.WinForms\&.ValueDrivenDirtyTracker\&.IsDirty\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
