.TH "JBToolkit.XmlDoc" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.XmlDoc
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConverters\fP"
.br
.ti -1c
.RI "namespace \fBMailMerge\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImageExtractor\fP"
.br
.RI "Uses a command line tool to extract all images found in an MS Office (docx, xlsx, msg, eml, pptx, vsdx, pub), PDF or HTMl document to a new folder "
.ti -1c
.RI "class \fBParser\fP"
.br
.RI "Parses and returns the text an MS Office document (docx, xlsx, msg, eml, pptx, vsdx, pub), PDF, or Image (using OCR) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
