.TH "JBToolkit.WinForms.CustomToolTip.ToolTipControl" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.CustomToolTip.ToolTipControl \- Provides information about ToolTips that are associated with their controls\&. This structure is used specifically with the 'GetToolTip(control)' method\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBControl\fP \fBControl\fP"
.br
.ti -1c
.RI "string \fBTitle\fP"
.br
.ti -1c
.RI "string \fBDescription\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides information about ToolTips that are associated with their controls\&. This structure is used specifically with the 'GetToolTip(control)' method\&. 


.SH "Member Data Documentation"
.PP 
.SS "\fBControl\fP JBToolkit\&.WinForms\&.CustomToolTip\&.ToolTipControl\&.Control"

.SS "string JBToolkit\&.WinForms\&.CustomToolTip\&.ToolTipControl\&.Description"

.SS "string JBToolkit\&.WinForms\&.CustomToolTip\&.ToolTipControl\&.Title"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
