.TH "JBToolkit.InterProcessComms.MemoryMappedFiles.SharedMemoryServer" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.MemoryMappedFiles.SharedMemoryServer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSharedMemoryServer\fP ()"
.br
.ti -1c
.RI "\fBSharedMemoryServer\fP (string mapFilename)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBDataReceivedEventArgs\fP > \fBReceived\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\&.SharedMemoryServer ()"

.SS "JBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\&.SharedMemoryServer (string mapFilename)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\&.Start ()"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SS "void JBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\&.Stop ()"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBDataReceivedEventArgs\fP> JBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\&.Received"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
