.TH "JBToolkit.Database.DBResult" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Database.DBResult \- Results object from a DB command  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.Database\&.DBResult\&.FailureDBCommandResult\fP, and \fBJBToolkit\&.Database\&.DBResult\&.SuccessDBCommandResult\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFailureDBCommandResult\fP"
.br
.ti -1c
.RI "class \fBSuccessDBCommandResult\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBFormatElapsedTime\fP (TimeSpan? ts)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBSuccess\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMessage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "object \fBResult\fP = string\&.Empty\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBElapsedTime\fP = null\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Results object from a DB command 


.SH "Member Function Documentation"
.PP 
.SS "static string JBToolkit\&.Database\&.DBResult\&.FormatElapsedTime (TimeSpan? ts)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Database\&.DBResult\&.ElapsedTime = null\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Database\&.DBResult\&.Message\fC [get]\fP, \fC [set]\fP"

.SS "object JBToolkit\&.Database\&.DBResult\&.Result = string\&.Empty\fC [get]\fP, \fC [set]\fP"

.SS "bool JBToolkit\&.Database\&.DBResult\&.Success\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
