.TH "JBToolkit.Database.DBResult.SuccessDBCommandResult" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Database.DBResult.SuccessDBCommandResult
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.Database\&.DBResult\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSuccessDBCommandResult\fP (object result, TimeSpan? timeTaken=null)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBJBToolkit\&.Database\&.DBResult\&.SuccessDBCommandResult\&.SuccessDBCommandResult\fP (object result, TimeSpan? timeTaken = \fCnull\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
