.TH "JBToolkit.ConsoleHelper.Options.OptionValueCollection" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options.OptionValueCollection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIList\fP, and \fBIList< string >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (string item)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBContains\fP (string item)"
.br
.ti -1c
.RI "void \fBCopyTo\fP (string[] array, int arrayIndex)"
.br
.ti -1c
.RI "bool \fBRemove\fP (string item)"
.br
.ti -1c
.RI "\fBIEnumerator\fP< string > \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "int \fBIndexOf\fP (string item)"
.br
.ti -1c
.RI "void \fBInsert\fP (int index, string item)"
.br
.ti -1c
.RI "void \fBRemoveAt\fP (int index)"
.br
.ti -1c
.RI "\fBList\fP< string > \fBToList\fP ()"
.br
.ti -1c
.RI "string[] \fBToArray\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBIsSynchronized\fP => (values as ICollection)\&.IsSynchronized"
.br
.ti -1c
.RI "object \fBSyncRoot\fP => (values as ICollection)\&.SyncRoot"
.br
.ti -1c
.RI "bool \fBIsFixedSize\fP => false"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsReadOnly\fP\fC [get]\fP"
.br
.ti -1c
.RI "string? \fBthis[int index]\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.Add (string item)"

.SS "void JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.Clear ()"

.SS "bool JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.Contains (string item)"

.SS "void JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.CopyTo (string[] array, int arrayIndex)"

.SS "\fBIEnumerator\fP<string> JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.GetEnumerator ()"

.SS "int JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.IndexOf (string item)"

.SS "void JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.Insert (int index, string item)"

.SS "bool JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.Remove (string item)"

.SS "void JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.RemoveAt (int index)"

.SS "string [] JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.ToArray ()"

.SS "\fBList\fP<string> JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.ToList ()"

.SS "override string JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.ToString ()"

.SH "Member Data Documentation"
.PP 
.SS "bool JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.IsFixedSize => false"

.SS "bool JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.IsSynchronized => (values as ICollection)\&.IsSynchronized"

.SS "object JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.SyncRoot => (values as ICollection)\&.SyncRoot"

.SH "Property Documentation"
.PP 
.SS "int JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.Count\fC [get]\fP"

.SS "bool JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.IsReadOnly\fC [get]\fP"

.SS "string? JBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\&.this[int index]\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
