.TH "JBToolkit.GoogeApi.Geocoding.GoogleGeolocationObject" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.GoogeApi.Geocoding.GoogleGeolocationObject
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBResult\fP[] \fBresults\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBstatus\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBResult\fP [] JBToolkit\&.GoogeApi\&.Geocoding\&.GoogleGeolocationObject\&.results\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.GoogeApi\&.Geocoding\&.GoogleGeolocationObject\&.status\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
