.TH "JBToolkit.FuzzyLogic.Algorithms.QuickFuzzyMatch" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.FuzzyLogic.Algorithms.QuickFuzzyMatch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.FuzzyLogic\&.Algorithms\&.BestFuzzyMatch\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBMatch\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "bool JBToolkit\&.FuzzyLogic\&.Algorithms\&.QuickFuzzyMatch\&.Match\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
