.TH "JBToolkit.PdfDoc.PdfConvertException" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.PdfDoc.PdfConvertException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBException\fP\&.
.PP
Inherited by \fBJBToolkit\&.PdfDoc\&.PdfConvertTimeoutException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPdfConvertException\fP ()"
.br
.ti -1c
.RI "\fBPdfConvertException\fP (string \fBmsg\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPdfConvertException\fP (SerializationInfo serializationInfo, StreamingContext streamingContext)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.PdfDoc\&.PdfConvertException\&.PdfConvertException ()"

.SS "JBToolkit\&.PdfDoc\&.PdfConvertException\&.PdfConvertException (string msg)"

.SS "JBToolkit\&.PdfDoc\&.PdfConvertException\&.PdfConvertException (SerializationInfo serializationInfo, StreamingContext streamingContext)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
