.TH "JBToolkit.Windows.ConsoleHelper.CommandOptionSet" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Windows.ConsoleHelper.CommandOptionSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionSet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandOptionSet\fP (\fBCommandSet\fP commands, \fBMessageLocalizerConverter\fP localizer)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBSetItem\fP (int index, \fBOption\fP item)"
.br
.ti -1c
.RI "override void \fBInsertItem\fP (int index, \fBOption\fP item)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Windows\&.ConsoleHelper\&.CommandOptionSet\&.CommandOptionSet (\fBCommandSet\fP commands, \fBMessageLocalizerConverter\fP localizer)"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.Windows\&.ConsoleHelper\&.CommandOptionSet\&.InsertItem (int index, \fBOption\fP item)\fC [protected]\fP"

.SS "override void JBToolkit\&.Windows\&.ConsoleHelper\&.CommandOptionSet\&.SetItem (int index, \fBOption\fP item)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
