.TH "JBToolkit.WinForms.Popup" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.Popup \- Simple, nice general popup with a delay before dissappearing  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBForm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopup\fP (string message, int durationInSeconds)"
.br
.ti -1c
.RI "\fBPopup\fP (string message)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override CreateParams \fBCreateParams\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple, nice general popup with a delay before dissappearing 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.Popup\&.Popup (string message, int durationInSeconds)"

.SS "JBToolkit\&.WinForms\&.Popup\&.Popup (string message)"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.Popup\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "override CreateParams JBToolkit\&.WinForms\&.Popup\&.CreateParams\fC [get]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
