.TH "JBToolkit.GoogeApi.Geocoding.Geometry" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.GoogeApi.Geocoding.Geometry
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLocation\fP \fBlocation\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlocation_type\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBViewport\fP \fBviewport\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBLocation\fP JBToolkit\&.GoogeApi\&.Geocoding\&.Geometry\&.location\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.GoogeApi\&.Geocoding\&.Geometry\&.location_type\fC [get]\fP, \fC [set]\fP"

.SS "\fBViewport\fP JBToolkit\&.GoogeApi\&.Geocoding\&.Geometry\&.viewport\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
