.TH "JBToolkit.Web" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Web
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccessLog\fP"
.br
.RI "Used to store remote access logs into the databse "
.ti -1c
.RI "class \fBAccessToken\fP"
.br
.RI "Generates and validates short lives access tokens - Stores in a database "
.ti -1c
.RI "class \fBEmail\fP"
.br
.RI "Contains methods for validating and sending emails (validating being thing such as validating the attached file size or extention) "
.ti -1c
.RI "class \fBEmailResult\fP"
.br
.RI "Contains email sent status information "
.ti -1c
.RI "class \fBFailureEmailResult\fP"
.br
.RI "Contains email sent 'success' information "
.ti -1c
.RI "class \fBHttp\fP"
.br
.RI "Generic HTTP methods "
.ti -1c
.RI "class \fBIPHelper\fP"
.br
.ti -1c
.RI "class \fBMemoryFile\fP"
.br
.RI "Inherits from '\fBHttpPostedFileBase\fP' - Used to create email attachments, and takes a Stream or MemoryStream) "
.ti -1c
.RI "class \fBSuccessEmailResult\fP"
.br
.RI "Contains email sent 'success' information "
.ti -1c
.RI "class \fBUrl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
