.TH "JBToolkit.Views.JQFRow" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.JQFRow
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBRowTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSubtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBImageURL\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBButtonAreaText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBContent\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< \fBJQFRowHighlightStrip\fP > \fBFirstRowHighlightStrips\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< \fBJQFRowHighlightStrip\fP > \fBSecondRowHighlightStrips\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< \fBJQFButton\fP > \fBButtons\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Views\&.JQFRow\&.ButtonAreaText\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<\fBJQFButton\fP> JBToolkit\&.Views\&.JQFRow\&.Buttons\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQFRow\&.Content\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<\fBJQFRowHighlightStrip\fP> JBToolkit\&.Views\&.JQFRow\&.FirstRowHighlightStrips\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQFRow\&.ImageURL\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQFRow\&.RowTitle\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<\fBJQFRowHighlightStrip\fP> JBToolkit\&.Views\&.JQFRow\&.SecondRowHighlightStrips\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Views\&.JQFRow\&.Subtitle\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
