.TH "JBToolkit.Views.DataTableSearch" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.DataTableSearch
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataTableSearch\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBregex\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Views\&.DataTableSearch\&.DataTableSearch ()"

.SH "Member Data Documentation"
.PP 
.SS "bool JBToolkit\&.Views\&.DataTableSearch\&.regex"

.SS "string JBToolkit\&.Views\&.DataTableSearch\&.value"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
