.TH "JBToolkit.InterProcessComms.IIpcClient" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.IIpcClient
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryClient\fP, \fBJBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueClient\fP, \fBJBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeClient\fP, \fBJBToolkit\&.InterProcessComms\&.NetRemoting\&.RemoteObject\fP, \fBJBToolkit\&.InterProcessComms\&.NetRemoting\&.RemotingClient\fP, \fBJBToolkit\&.InterProcessComms\&.Sockets\&.SocketClient\fP, \fBJBToolkit\&.InterProcessComms\&.Wcf\&.WcfClient\fP, and \fBJBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.CopyDataClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSend\fP (string data)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.IIpcClient\&.Send (string data)"

.PP
Implemented in \fBJBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.CopyDataClient\fP, \fBJBToolkit\&.InterProcessComms\&.Wcf\&.WcfClient\fP, \fBJBToolkit\&.InterProcessComms\&.Sockets\&.SocketClient\fP, \fBJBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeClient\fP, \fBJBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueClient\fP, \fBJBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryClient\fP, and \fBJBToolkit\&.InterProcessComms\&.NetRemoting\&.RemotingClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
