.TH "JBToolkit.Zip.FilePathAndBytesCollection" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Zip.FilePathAndBytesCollection \- A basic dictionary of the filename to save within the zip file and the bytes of that file  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBList< FilePathAndBytes >\fP\&.
.SH "Detailed Description"
.PP 
A basic dictionary of the filename to save within the zip file and the bytes of that file 



.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
