.TH "JBToolkit.Images.ImageHelper.HtmlImageHelper.HtmlPath" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Images.ImageHelper.HtmlImageHelper.HtmlPath \- Paths to image in Html file along with a path type (i\&.e\&. local, relative, remote, data)  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPathTypeEnum\fP { \fBPathTypeEnum\&.Remote\fP, \fBPathTypeEnum\&.LocalFull\fP, \fBPathTypeEnum\&.LocalRelative\fP, \fBPathTypeEnum\&.Data\fP }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPathTypeEnum\fP \fBPathType\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Paths to image in Html file along with a path type (i\&.e\&. local, relative, remote, data) 


.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBJBToolkit\&.Images\&.ImageHelper\&.HtmlImageHelper\&.HtmlPath\&.PathTypeEnum\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRemote \fP\fP
.TP
\fB\fILocalFull \fP\fP
.TP
\fB\fILocalRelative \fP\fP
.TP
\fB\fIData \fP\fP
.SH "Property Documentation"
.PP 
.SS "\fBPathTypeEnum\fP JBToolkit\&.Images\&.ImageHelper\&.HtmlImageHelper\&.HtmlPath\&.PathType\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Images\&.ImageHelper\&.HtmlImageHelper\&.HtmlPath\&.Value\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
