.TH "JBToolkit.WinForms.ControlDirtyTrackerCollection" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.ControlDirtyTrackerCollection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBList< ControlDirtyTracker >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControlDirtyTrackerCollection\fP ()"
.br
.ti -1c
.RI "\fBControlDirtyTrackerCollection\fP (\fBForm\fP frm)"
.br
.ti -1c
.RI "void \fBAddControlsFromForm\fP (\fBForm\fP frm)"
.br
.ti -1c
.RI "void \fBAddControlsFromCollection\fP (Control\&.ControlCollection coll)"
.br
.ti -1c
.RI "\fBList\fP< \fBControl\fP > \fBGetListOfDirtyControls\fP ()"
.br
.ti -1c
.RI "void \fBMarkAllControlsAsClean\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.ControlDirtyTrackerCollection\&.ControlDirtyTrackerCollection ()"

.SS "JBToolkit\&.WinForms\&.ControlDirtyTrackerCollection\&.ControlDirtyTrackerCollection (\fBForm\fP frm)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.WinForms\&.ControlDirtyTrackerCollection\&.AddControlsFromCollection (Control\&.ControlCollection coll)"

.SS "void JBToolkit\&.WinForms\&.ControlDirtyTrackerCollection\&.AddControlsFromForm (\fBForm\fP frm)"

.SS "\fBList\fP<\fBControl\fP> JBToolkit\&.WinForms\&.ControlDirtyTrackerCollection\&.GetListOfDirtyControls ()"

.SS "void JBToolkit\&.WinForms\&.ControlDirtyTrackerCollection\&.MarkAllControlsAsClean ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
