.TH "JBToolkit.WinForms.ColourHelper.IntensityGenerator" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.ColourHelper.IntensityGenerator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBNextIntensity\fP (int index)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string JBToolkit\&.WinForms\&.ColourHelper\&.IntensityGenerator\&.NextIntensity (int index)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
