.TH "JBToolkit.InterProcessComms.MemoryMappedFiles" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.MemoryMappedFiles \- Memory-mapped files in \fBWindows\fP allow us to either map a “window” of a large file on the filesystem, or to create a named memory area that can be shared among processes\&. A shared area on the fly is created and uses named AutoResetEvents to control access to it\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSharedMemoryClient\fP"
.br
.ti -1c
.RI "class \fBSharedMemoryServer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Memory-mapped files in \fBWindows\fP allow us to either map a “window” of a large file on the filesystem, or to create a named memory area that can be shared among processes\&. A shared area on the fly is created and uses named AutoResetEvents to control access to it\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
