.TH "JBToolkit.ConsoleHelper.Options" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArgumentSource\fP"
.br
.ti -1c
.RI "class \fBCommand\fP"
.br
.ti -1c
.RI "class \fBCommandOption\fP"
.br
.ti -1c
.RI "class \fBCommandOptionSet\fP"
.br
.ti -1c
.RI "class \fBCommandSet\fP"
.br
.ti -1c
.RI "class \fBHelpCommand\fP"
.br
.ti -1c
.RI "class \fBHelpOption\fP"
.br
.ti -1c
.RI "class \fBOption\fP"
.br
.RI "User Guide: http://docs.go-mono.com/index.aspx?link=T:Mono.Options.OptionSet "
.ti -1c
.RI "class \fBOptionContext\fP"
.br
.ti -1c
.RI "class \fBOptionException\fP"
.br
.ti -1c
.RI "class \fBOptionSet\fP"
.br
.ti -1c
.RI "class \fBOptionValueCollection\fP"
.br
.ti -1c
.RI "class \fBResponseFileSource\fP"
.br
.ti -1c
.RI "class \fBStringCoda\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBOptionValueType\fP { \fBOptionValueType\&.None\fP, \fBOptionValueType\&.Optional\fP, \fBOptionValueType\&.Required\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBOptionAction< TKey, TValue >\fP (TKey key, TValue value)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionValueType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIOptional \fP\fP
.TP
\fB\fIRequired \fP\fP
.SH "Function Documentation"
.PP 
.SS "delegate void JBToolkit\&.ConsoleHelper\&.Options\&.OptionAction< TKey, TValue > (TKey key, TValue value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
