.TH "JBToolkit.ConsoleHelper.Options.ResponseFileSource" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options.ResponseFileSource
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.ConsoleHelper\&.Options\&.ArgumentSource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string[] \fBGetNames\fP ()"
.br
.ti -1c
.RI "override bool \fBGetArguments\fP (string value, out \fBIEnumerable\fP< string > replacement)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBDescription\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override bool JBToolkit\&.ConsoleHelper\&.Options\&.ResponseFileSource\&.GetArguments (string value, out \fBIEnumerable\fP< string > replacement)\fC [virtual]\fP"

.PP
Implements \fBJBToolkit\&.ConsoleHelper\&.Options\&.ArgumentSource\fP\&.
.SS "override string [] JBToolkit\&.ConsoleHelper\&.Options\&.ResponseFileSource\&.GetNames ()\fC [virtual]\fP"

.PP
Implements \fBJBToolkit\&.ConsoleHelper\&.Options\&.ArgumentSource\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string JBToolkit\&.ConsoleHelper\&.Options\&.ResponseFileSource\&.Description\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
