.TH "JBToolkit.GoogeApi" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.GoogeApi
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeocoding\fP"
.br
.RI "Perform geocoding operations on longitue and latitude or reverse-geocoding (i\&.e\&. long lat from address)\&. Can Get the full Google geocoding object or just the desired formatted address or lat long coordinates "
.ti -1c
.RI "class \fBVision\fP"
.br
.RI "Perform OCR operation using Google's \fBVision\fP API "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
