.TH "JBToolkit.Windows.ConsoleHelper.OptionException" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Windows.ConsoleHelper.OptionException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionException\fP ()"
.br
.ti -1c
.RI "\fBOptionException\fP (string message, string optionName)"
.br
.ti -1c
.RI "\fBOptionException\fP (string message, string optionName, \fBException\fP innerException)"
.br
.ti -1c
.RI "override void \fBGetObjectData\fP (SerializationInfo info, StreamingContext context)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionException\fP (SerializationInfo info, StreamingContext context)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBOptionName\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Windows\&.ConsoleHelper\&.OptionException\&.OptionException ()"

.SS "JBToolkit\&.Windows\&.ConsoleHelper\&.OptionException\&.OptionException (string message, string optionName)"

.SS "JBToolkit\&.Windows\&.ConsoleHelper\&.OptionException\&.OptionException (string message, string optionName, \fBException\fP innerException)"

.SS "JBToolkit\&.Windows\&.ConsoleHelper\&.OptionException\&.OptionException (SerializationInfo info, StreamingContext context)\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.Windows\&.ConsoleHelper\&.OptionException\&.GetObjectData (SerializationInfo info, StreamingContext context)"

.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Windows\&.ConsoleHelper\&.OptionException\&.OptionName\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
