.TH "JBToolkit.WinForms.ScrollingListBox" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.ScrollingListBox \- Event handling for 'scoll' of listbox - Can come in handy, say if you want to scroll two list boxes simultaneously  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBListBox\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBWndProc\fP (ref System\&.Windows\&.Forms\&.Message \fBmsg\fP)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "ScrollEventHandler \fBOnHorizontalScroll\fP"
.br
.ti -1c
.RI "ScrollEventHandler \fBOnVerticalScroll\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event handling for 'scoll' of listbox - Can come in handy, say if you want to scroll two list boxes simultaneously 


.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.ScrollingListBox\&.WndProc (ref System\&.Windows\&.Forms\&.Message msg)\fC [protected]\fP"

.SH "Event Documentation"
.PP 
.SS "ScrollEventHandler JBToolkit\&.WinForms\&.ScrollingListBox\&.OnHorizontalScroll"

.SS "ScrollEventHandler JBToolkit\&.WinForms\&.ScrollingListBox\&.OnVerticalScroll"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
