.TH "JBToolkit.WinForms.HtmlLabel" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.HtmlLabel \- Provides HTML rendering on the text of the label  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.WinForms\&.HtmlPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHtmlLabel\fP ()"
.br
.RI "Creates a new HTML Label "
.ti -1c
.RI "override void \fBMeasureBounds\fP ()"
.br
.RI "Measures the bounds of the container "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBAutoSize\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Provides HTML rendering on the text of the label 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.HtmlLabel\&.HtmlLabel ()"

.PP
Creates a new HTML Label 
.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.HtmlLabel\&.MeasureBounds ()\fC [virtual]\fP"

.PP
Measures the bounds of the container 
.PP
Reimplemented from \fBJBToolkit\&.WinForms\&.HtmlPanel\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool JBToolkit\&.WinForms\&.HtmlLabel\&.AutoSize\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
