.TH "JBToolkit.Views.DataTableResultError" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.DataTableResultError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.Views\&.DataTableResultSet\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBerror\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "string JBToolkit\&.Views\&.DataTableResultError\&.error"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
