.TH "JBToolkit.SharePoint.REST.Authentication" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.SharePoint.REST.Authentication \- Authenticate with \fBSharePoint\fP using the \fBREST\fP API  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetAccessToken\fP (string siteName, string tenantId, string clientId, string clientSecret)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Authenticate with \fBSharePoint\fP using the \fBREST\fP API 


.SH "Member Function Documentation"
.PP 
.SS "static string JBToolkit\&.SharePoint\&.REST\&.Authentication\&.GetAccessToken (string siteName, string tenantId, string clientId, string clientSecret)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
