.TH "JBToolkit.Database.DBGeneric" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Database.DBGeneric \- Use to initialise the simplest DB class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.Database\&.DBConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDBGeneric\fP (string dbname, string connectionString, string applicationName)"
.br
.ti -1c
.RI "\fBDBGeneric\fP (string dbname, string connectionString)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Use to initialise the simplest DB class 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Database\&.DBGeneric\&.DBGeneric (string dbname, string connectionString, string applicationName)"

.SS "JBToolkit\&.Database\&.DBGeneric\&.DBGeneric (string dbname, string connectionString)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
