.TH "JBToolkit.Views.JQTSorting" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.JQTSorting \- Sort direction and column index object  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBSortByColumnIndex\fP = 0\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBJQTSortDirection\fP? \fBSortDirection\fP = \fBJQTSortDirection\&.ASCENDING\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sort direction and column index object 


.SH "Property Documentation"
.PP 
.SS "int JBToolkit\&.Views\&.JQTSorting\&.SortByColumnIndex = 0\fC [get]\fP, \fC [set]\fP"

.SS "\fBJQTSortDirection\fP? JBToolkit\&.Views\&.JQTSorting\&.SortDirection = \fBJQTSortDirection\&.ASCENDING\fP\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
