.TH "JBToolkit.SharePoint.CSOM.Objects.FileFolderCollection" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.SharePoint.CSOM.Objects.FileFolderCollection
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "FileCollection \fBFiles\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "FolderCollection \fBFolders\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "FileCollection JBToolkit\&.SharePoint\&.CSOM\&.Objects\&.FileFolderCollection\&.Files\fC [get]\fP, \fC [set]\fP"

.SS "FolderCollection JBToolkit\&.SharePoint\&.CSOM\&.Objects\&.FileFolderCollection\&.Folders\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
