.TH "JBToolkit.InterProcessComms.WM_COPYDATA.CopyDataClient" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.WM_COPYDATA.CopyDataClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyDataClient\fP ()"
.br
.ti -1c
.RI "\fBCopyDataClient\fP (string wcName)"
.br
.ti -1c
.RI "void \fBSend\fP (string data)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.CopyDataClient\&.CopyDataClient ()"

.SS "JBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.CopyDataClient\&.CopyDataClient (string wcName)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.CopyDataClient\&.Send (string data)"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
