.TH "JBToolkit.ConsoleHelper.Options.HelpCommand" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options.HelpCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.ConsoleHelper\&.Options\&.Command\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpCommand\fP ()"
.br
.ti -1c
.RI "override int \fBInvoke\fP (\fBIEnumerable\fP< string > arguments)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.ConsoleHelper\&.Options\&.HelpCommand\&.HelpCommand ()"

.SH "Member Function Documentation"
.PP 
.SS "override int JBToolkit\&.ConsoleHelper\&.Options\&.HelpCommand\&.Invoke (\fBIEnumerable\fP< string > arguments)\fC [virtual]\fP"

.PP
Reimplemented from \fBJBToolkit\&.ConsoleHelper\&.Options\&.Command\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
