.TH "JBToolkit.Domain.Impersonation.Impersonator.ImpersonatorCredentials" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Domain.Impersonation.Impersonator.ImpersonatorCredentials
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBImpersonatorCredentials\fP \fBGetImpersonatatorCredentials\fP (\fBServerType\fP serverType, string credentialUsename, string credentialPassword, string dmzHost=null)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUsername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPassword\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDomain\fP = Environment\&.UserDomainName\fC [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBImpersonatorCredentials\fP JBToolkit\&.Domain\&.Impersonation\&.Impersonator\&.ImpersonatorCredentials\&.GetImpersonatatorCredentials (\fBServerType\fP serverType, string credentialUsename, string credentialPassword, string dmzHost = \fCnull\fP)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Domain\&.Impersonation\&.Impersonator\&.ImpersonatorCredentials\&.Domain = Environment\&.UserDomainName\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.Impersonation\&.Impersonator\&.ImpersonatorCredentials\&.Password\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Domain\&.Impersonation\&.Impersonator\&.ImpersonatorCredentials\&.Username\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
