.TH "JBToolkit.InterProcessComms.DataReceivedEventArgs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.DataReceivedEventArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataReceivedEventArgs\fP (string data)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.DataReceivedEventArgs\&.DataReceivedEventArgs (string data)"

.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.InterProcessComms\&.DataReceivedEventArgs\&.Data\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
