.TH "JBToolkit.InterProcessComms.NamedPipes.NamedPipeServer" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.NamedPipes.NamedPipeServer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNamedPipeServer\fP ()"
.br
.ti -1c
.RI "\fBNamedPipeServer\fP (string pipeName)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBDataReceivedEventArgs\fP > \fBReceived\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeServer\&.NamedPipeServer ()"

.SS "JBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeServer\&.NamedPipeServer (string pipeName)"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeServer\&.Start ()"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SS "void JBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeServer\&.Stop ()"

.PP
Implements \fBJBToolkit\&.InterProcessComms\&.IIpcServer\fP\&.
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBDataReceivedEventArgs\fP> JBToolkit\&.InterProcessComms\&.NamedPipes\&.NamedPipeServer\&.Received"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
