.TH "JBToolkit.Windows.WindowHelper.RECT" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Windows.WindowHelper.RECT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBleft\fP"
.br
.ti -1c
.RI "int \fBtop\fP"
.br
.ti -1c
.RI "int \fBright\fP"
.br
.ti -1c
.RI "int \fBbottom\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int JBToolkit\&.Windows\&.WindowHelper\&.RECT\&.bottom"

.SS "int JBToolkit\&.Windows\&.WindowHelper\&.RECT\&.left"

.SS "int JBToolkit\&.Windows\&.WindowHelper\&.RECT\&.right"

.SS "int JBToolkit\&.Windows\&.WindowHelper\&.RECT\&.top"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
