.TH "JBToolkit.RegularExpressions" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.RegularExpressions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommon\fP"
.br
.ti -1c
.RI "class \fBCountryPostCodes\fP"
.br
.ti -1c
.RI "class \fBDateTimeHelper\fP"
.br
.RI "Methods for DateTime search, validation and manipulation "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
