.TH "JBToolkit.Views.DataTableColumn" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Views.DataTableColumn
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataTableColumn\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBdata\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "bool \fBsearchable\fP"
.br
.ti -1c
.RI "bool \fBorderable\fP"
.br
.ti -1c
.RI "\fBDataTableSearch\fP \fBsearch\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Views\&.DataTableColumn\&.DataTableColumn ()"

.SH "Member Data Documentation"
.PP 
.SS "string JBToolkit\&.Views\&.DataTableColumn\&.data"

.SS "string JBToolkit\&.Views\&.DataTableColumn\&.name"

.SS "bool JBToolkit\&.Views\&.DataTableColumn\&.orderable"

.SS "\fBDataTableSearch\fP JBToolkit\&.Views\&.DataTableColumn\&.search"

.SS "bool JBToolkit\&.Views\&.DataTableColumn\&.searchable"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
