.TH "JBToolkit.InterProcessComms.MessageQueues" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.MessageQueues \- \fBWindows\fP has included a message queues implementation for a long time, something that is often forgotten by developers\&. If you don’t have it installed – you can check if the Message Queuing service exists – you can install it through Programs and Features – Turn \fBWindows\fP features on and off on the \fBControl\fP Panel\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMessageQueueClient\fP"
.br
.ti -1c
.RI "class \fBMessageQueueServer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWindows\fP has included a message queues implementation for a long time, something that is often forgotten by developers\&. If you don’t have it installed – you can check if the Message Queuing service exists – you can install it through Programs and Features – Turn \fBWindows\fP features on and off on the \fBControl\fP Panel\&. 

Gist from: https://weblogs.asp.net/ricardoperes/local-machine-interprocess-communication-with-net
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
