.TH "JBToolkit.Zip.Native.ZipArchive.ZipFileInfo" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Zip.Native.ZipArchive.ZipFileInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override string JBToolkit\&.Zip\&.Native\&.ZipArchive\&.ZipFileInfo\&.ToString ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
