.TH "JBToolkit.WinForms.ImageButton" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.ImageButton \- Image as button (with Cursor swap)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBButton\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnMouseEnter\fP (\fBEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBOnMouseLeave\fP (\fBEventArgs\fP e)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "override bool \fBShowFocusCues\fP => false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Image as button (with Cursor swap) 


.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.ImageButton\&.OnMouseEnter (\fBEventArgs\fP e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.ImageButton\&.OnMouseLeave (\fBEventArgs\fP e)\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "override bool JBToolkit\&.WinForms\&.ImageButton\&.ShowFocusCues => false\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
