.TH "JBToolkit.InterProcessComms.NamedPipes" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.NamedPipes \- Named pipes in \fBWindows\fP is a duplex means of sending data between \fBWindows\fP hosts\&. We used it in the WCF implementation, but \&.NET has its own built-in support for named pipes communication\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNamedPipeClient\fP"
.br
.ti -1c
.RI "class \fBNamedPipeServer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Named pipes in \fBWindows\fP is a duplex means of sending data between \fBWindows\fP hosts\&. We used it in the WCF implementation, but \&.NET has its own built-in support for named pipes communication\&. 

Gist from: https://weblogs.asp.net/ricardoperes/local-machine-interprocess-communication-with-net
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
