.TH "JBToolkit" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAssemblyHelper\fP"
.br
.ti -1c
.RI "namespace \fBConsoleHelper\fP"
.br
.ti -1c
.RI "namespace \fBCsv\fP"
.br
.ti -1c
.RI "namespace \fBDatabase\fP"
.br
.ti -1c
.RI "namespace \fBDomain\fP"
.br
.ti -1c
.RI "namespace \fBEncryption\fP"
.br
.ti -1c
.RI "namespace \fBExtensions\fP"
.br
.ti -1c
.RI "namespace \fBFuzzyLogic\fP"
.br
.ti -1c
.RI "namespace \fBGoogeApi\fP"
.br
.ti -1c
.RI "namespace \fBImages\fP"
.br
.ti -1c
.RI "namespace \fBInterProcessComms\fP"
.br
.RI "Gist from: https://weblogs.asp.net/ricardoperes/local-machine-interprocess-communication-with-netD "
.ti -1c
.RI "namespace \fBLogger\fP"
.br
.ti -1c
.RI "namespace \fBPdfDoc\fP"
.br
.ti -1c
.RI "namespace \fBRegularExpressions\fP"
.br
.ti -1c
.RI "namespace \fBSharePoint\fP"
.br
.ti -1c
.RI "namespace \fBStreams\fP"
.br
.ti -1c
.RI "namespace \fBViews\fP"
.br
.ti -1c
.RI "namespace \fBWeb\fP"
.br
.ti -1c
.RI "namespace \fBWindows\fP"
.br
.ti -1c
.RI "namespace \fBWinForms\fP"
.br
.ti -1c
.RI "namespace \fBXmlDoc\fP"
.br
.ti -1c
.RI "namespace \fBZip\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
