.TH "JBToolkit.PdfDoc.PdfConvertEnvironment" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.PdfDoc.PdfConvertEnvironment
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTempFolderPath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBWkHtmlToPdfPath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBTimeout\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBDebug\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "bool JBToolkit\&.PdfDoc\&.PdfConvertEnvironment\&.Debug\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertEnvironment\&.TempFolderPath\fC [get]\fP, \fC [set]\fP"

.SS "int JBToolkit\&.PdfDoc\&.PdfConvertEnvironment\&.Timeout\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertEnvironment\&.WkHtmlToPdfPath\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
