.TH "JBToolkit.XmlDoc.ImageExtractor" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.XmlDoc.ImageExtractor \- Uses a command line tool to extract all images found in an MS Office (docx, xlsx, msg, eml, pptx, vsdx, pub), PDF or HTMl document to a new folder  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBExtractImagesFromDocument\fP (string inputPath, string outputDirectory, int timeoutSeconds=60)"
.br
.RI "Uses a command line tool to extract all images found in an MS Office (docx, xlsx, msg, eml, pptx, vsdx, pub), PDF or HTMl document to a new folder "
.in -1c
.SH "Detailed Description"
.PP 
Uses a command line tool to extract all images found in an MS Office (docx, xlsx, msg, eml, pptx, vsdx, pub), PDF or HTMl document to a new folder 


.SH "Member Function Documentation"
.PP 
.SS "static void JBToolkit\&.XmlDoc\&.ImageExtractor\&.ExtractImagesFromDocument (string inputPath, string outputDirectory, int timeoutSeconds = \fC60\fP)\fC [static]\fP"

.PP
Uses a command line tool to extract all images found in an MS Office (docx, xlsx, msg, eml, pptx, vsdx, pub), PDF or HTMl document to a new folder 
.PP
\fBParameters\fP
.RS 4
\fIinputPath\fP Document input path
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
