.TH "JBToolkit.PdfDoc" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.PdfDoc
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPdfConverter\fP"
.br
.RI "Methods to convert Docx to PDF through M-Files\&. I've done it this way as it's costs a tonne for a docx to pdf converter license with the likes of Aspose, Spire, ABCpdf etc and M-Files is already using Aspose so just utilise that\&. The process involves uploading a file to M-Files, converting it to a PDF there, then downloading it as PDF and finally deleting (destroying) the file in the M-Files vault "
.ti -1c
.RI "class \fBPdfMerger\fP"
.br
.RI "Methods to merge PDF documents together, input either memory stream or path (or both) and output as memory stream or save to file "
.ti -1c
.RI "class \fBPdfParser\fP"
.br
.RI "PDF Parsing methods "
.ti -1c
.RI "class \fBPdfSplitter\fP"
.br
.RI "Methods to split up a PDF document with various criteria such as page quantity multiples, an array of page numbers to split after or actual string content (included regular expression matching) within the document itself\&. You can input and output a memory stream or save to file\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
