.TH "JBToolkit.PdfDoc.PdfConvertDocument" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.PdfDoc.PdfConvertDocument
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPaperType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBOrientation\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHtml\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHeaderUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFooterUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHeaderLeft\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHeaderCenter\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHeaderRight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFooterLeft\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFooterCenter\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFooterRight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "object \fBState\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, string > \fBCookies\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, string > \fBExtraParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHeaderFontSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFooterFontSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHeaderFontName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFooterFontName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "Dictionary<string, string> JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.Cookies\fC [get]\fP, \fC [set]\fP"

.SS "Dictionary<string, string> JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.ExtraParams\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.FooterCenter\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.FooterFontName\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.FooterFontSize\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.FooterLeft\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.FooterRight\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.FooterUrl\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.HeaderCenter\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.HeaderFontName\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.HeaderFontSize\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.HeaderLeft\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.HeaderRight\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.HeaderUrl\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.Html\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.Orientation\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.PaperType\fC [get]\fP, \fC [set]\fP"

.SS "object JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.State\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.PdfDoc\&.PdfConvertDocument\&.Url\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
