.TH "JBToolkit.WinForms.ControlDirtyTracker" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.ControlDirtyTracker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControlDirtyTracker\fP (\fBControl\fP ctl)"
.br
.ti -1c
.RI "void \fBEstablishValueAsClean\fP ()"
.br
.ti -1c
.RI "bool \fBDetermineIfDirty\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsControlTypeSupported\fP (\fBControl\fP ctl)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBControl\fP \fBControl\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBCleanValue\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.ControlDirtyTracker\&.ControlDirtyTracker (\fBControl\fP ctl)"

.SH "Member Function Documentation"
.PP 
.SS "bool JBToolkit\&.WinForms\&.ControlDirtyTracker\&.DetermineIfDirty ()"

.SS "void JBToolkit\&.WinForms\&.ControlDirtyTracker\&.EstablishValueAsClean ()"

.SS "static bool JBToolkit\&.WinForms\&.ControlDirtyTracker\&.IsControlTypeSupported (\fBControl\fP ctl)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.WinForms\&.ControlDirtyTracker\&.CleanValue\fC [get]\fP"

.SS "\fBControl\fP JBToolkit\&.WinForms\&.ControlDirtyTracker\&.Control\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
