.TH "JBToolkit.Extensions.SourceCode.SourceCodeFormatter.LenientJsonFormatter" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Extensions.SourceCode.SourceCodeFormatter.LenientJsonFormatter \- Use to format json without the use of serialisation, in order to try and ignore any syntax errors  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIndentWriter\fP"
.br
.ti -1c
.RI "class \fBStringWalker\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLenientJsonFormatter\fP (string json)"
.br
.RI "Use to format json without the use of serialisation, in order to try and ignore any syntax errors "
.ti -1c
.RI "void \fBResetLine\fP ()"
.br
.ti -1c
.RI "string \fBFormat\fP ()"
.br
.ti -1c
.RI "bool \fBIsApostrophe\fP ()"
.br
.ti -1c
.RI "bool \fBIsOpenBracket\fP ()"
.br
.ti -1c
.RI "bool \fBIsCloseBracket\fP ()"
.br
.ti -1c
.RI "bool \fBIsColon\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use to format json without the use of serialisation, in order to try and ignore any syntax errors 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.LenientJsonFormatter (string json)"

.PP
Use to format json without the use of serialisation, in order to try and ignore any syntax errors 
.SH "Member Function Documentation"
.PP 
.SS "string JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.Format ()"

.SS "bool JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IsApostrophe ()"

.SS "bool JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IsCloseBracket ()"

.SS "bool JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IsColon ()"

.SS "bool JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IsOpenBracket ()"

.SS "void JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.ResetLine ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
