.TH "JBToolkit.Zip.FilePathAndBytes" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Zip.FilePathAndBytes \- Filename to store within zip file and it's file as a byte array  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFilename\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBBytes\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filename to store within zip file and it's file as a byte array 


.SH "Property Documentation"
.PP 
.SS "byte [] JBToolkit\&.Zip\&.FilePathAndBytes\&.Bytes\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Zip\&.FilePathAndBytes\&.Filename\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
