.TH "JBToolkit.InterProcessComms.WM_COPYDATA.COPYDATASTRUCT" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.InterProcessComms.WM_COPYDATA.COPYDATASTRUCT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBdwData\fP"
.br
.ti -1c
.RI "IntPtr \fBcbData\fP"
.br
.ti -1c
.RI "IntPtr \fBlpData\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "IntPtr JBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.COPYDATASTRUCT\&.cbData"

.SS "IntPtr JBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.COPYDATASTRUCT\&.dwData"

.SS "IntPtr JBToolkit\&.InterProcessComms\&.WM_COPYDATA\&.COPYDATASTRUCT\&.lpData"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
