.TH "JBToolkit.Extensions.SourceCode.SourceCodeFormatter.LenientJsonFormatter.IndentWriter" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Extensions.SourceCode.SourceCodeFormatter.LenientJsonFormatter.IndentWriter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBIndent\fP ()"
.br
.ti -1c
.RI "void \fBUnIndent\fP ()"
.br
.ti -1c
.RI "void \fBWriteLine\fP (string line)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IndentWriter\&.Indent ()"

.SS "override string JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IndentWriter\&.ToString ()"

.SS "void JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IndentWriter\&.UnIndent ()"

.SS "void JBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IndentWriter\&.WriteLine (string line)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
