.TH "JBToolkit.ConsoleHelper.Options.OptionContext" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ConsoleHelper.Options.OptionContext
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionContext\fP (\fBOptionSet\fP set)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBOption\fP \fBOption\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBOptionName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBOptionIndex\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBOptionSet\fP \fBOptionSet\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBOptionValueCollection\fP \fBOptionValues\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.ConsoleHelper\&.Options\&.OptionContext\&.OptionContext (\fBOptionSet\fP set)"

.SH "Property Documentation"
.PP 
.SS "\fBOption\fP JBToolkit\&.ConsoleHelper\&.Options\&.OptionContext\&.Option\fC [get]\fP, \fC [set]\fP"

.SS "int JBToolkit\&.ConsoleHelper\&.Options\&.OptionContext\&.OptionIndex\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.ConsoleHelper\&.Options\&.OptionContext\&.OptionName\fC [get]\fP, \fC [set]\fP"

.SS "\fBOptionSet\fP JBToolkit\&.ConsoleHelper\&.Options\&.OptionContext\&.OptionSet\fC [get]\fP"

.SS "\fBOptionValueCollection\fP JBToolkit\&.ConsoleHelper\&.Options\&.OptionContext\&.OptionValues\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
