.TH "JBToolkit.Database.DataTableState" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Database.DataTableState
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTableID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTableSettings\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string JBToolkit\&.Database\&.DataTableState\&.TableID\fC [get]\fP, \fC [set]\fP"

.SS "string JBToolkit\&.Database\&.DataTableState\&.TableSettings\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
