.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/JQueryDataTableViewModels/JqueryFeed.cs" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/JQueryDataTableViewModels/JqueryFeed.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JqueryFeed\fP"
.br
.RI "Generates JQquery Feed HTML from a Model "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQFRow\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQFButton\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQFRowHighlightStrip\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Views\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
