.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/JQueryDataTableViewModels/JQueryDataTables/JqueryHtmlDataTable.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/JQueryDataTableViewModels/JQueryDataTables/JqueryHtmlDataTable.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JqueryHtmlDataTable\fP"
.br
.RI "Generates JQquery DataTable HTML from a model\&. "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQTHeader\fP"
.br
.RI "Header information "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQTRow\fP"
.br
.RI "\fBList\fP of columns "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQTColumn\fP"
.br
.RI "Individual column object "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQTSelectableDataSource\fP"
.br
.RI "You'll have to handle the javascript in the parent view, via creating an event handler referencing the given UniqueID "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQTSelectableDataSourceItem\fP"
.br
.RI "Iteams for SelectableDataSource "
.ti -1c
.RI "class \fBJBToolkit\&.Views\&.JQTSorting\fP"
.br
.RI "Sort direction and column index object "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Views\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJBToolkit\&.Views\&.HyperlinkTargetEnum\fP { \fBJBToolkit\&.Views\&.HyperlinkTargetEnum\&._blank\fP, \fBJBToolkit\&.Views\&.HyperlinkTargetEnum\&._self\fP, \fBJBToolkit\&.Views\&.HyperlinkTargetEnum\&._parent\fP, \fBJBToolkit\&.Views\&.HyperlinkTargetEnum\&._top\fP }"
.br
.RI "How to open a hyperlink "
.ti -1c
.RI "enum \fBJBToolkit\&.Views\&.JQTSortDirection\fP { \fBJBToolkit\&.Views\&.JQTSortDirection\&.ASCENDING\fP = 0, \fBJBToolkit\&.Views\&.JQTSortDirection\&.DECENDING\fP = 1 }"
.br
.RI "Column Sort Direction enum "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
