.TH "KeyedCollection" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyedCollection
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.Windows\&.ConsoleHelper\&.CommandSet\fP, and \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionSet\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
