.TH "KeyedCollection" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyedCollection
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.ConsoleHelper\&.Options\&.CommandSet\fP, and \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionSet\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
