.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/XmlDoc/Converters/OfficeToPDF-CLI-Notes/LICENSE.md" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/XmlDoc/Converters/OfficeToPDF-CLI-Notes/LICENSE.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
