.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/licenses/LICENSE.txt" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/licenses/LICENSE.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "MIT License \fBCopyright\fP (c) 2020 James Brindle Permission is hereby granted"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation \fBfiles\fP (the 'Software')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "MIT License free of \fBcharge\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without \fBrestriction\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to \fBuse\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a copy of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to \fBcopy\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to \fBmodify\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to \fBmerge\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to \fBpublish\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to \fBdistribute\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to \fBsublicense\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the Software without including without limitation the rights to and or sell copies of the \fBSoftware\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do \fBso\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following \fBconditions\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY \fBKIND\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR \fBIMPLIED\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF \fBMERCHANTABILITY\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY \fBCLAIM\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER \fBLIABILITY\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF \fBCONTRACT\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR \fBOTHERWISE\fP"
.br
.ti -1c
.RI "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR ARISING \fBFROM\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "MIT License Copyright (c)"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation files (the 'Software')"

.SH "Variable Documentation"
.PP 
.SS "MIT License free of charge"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following conditions"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF CONTRACT"

.SS "MIT License free of to any person obtaining a copy of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to copy"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to distribute"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR ARISING FROM"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR IMPLIED"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY KIND"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to merge"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to modify"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR OTHERWISE"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to publish"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without restriction"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do so"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the Software without including without limitation the rights to and or sell copies of the Software"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to sublicense"

.SS "MIT License free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to use"

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
