.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/InterProcessComms/MemoryMappedFile/MemoryMappedFilesServer.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/InterProcessComms/MemoryMappedFile/MemoryMappedFilesServer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.InterProcessComms\&.MemoryMappedFiles\&.SharedMemoryServer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.InterProcessComms\fP"
.br
.RI "Gist from: https://weblogs.asp.net/ricardoperes/local-machine-interprocess-communication-with-netD "
.ti -1c
.RI "namespace \fBJBToolkit\&.InterProcessComms\&.MemoryMappedFiles\fP"
.br
.RI "Memory-mapped files in \fBWindows\fP allow us to either map a “window” of a large file on the filesystem, or to create a named memory area that can be shared among processes\&. A shared area on the fly is created and uses named AutoResetEvents to control access to it\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
