.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/InterProcessComms/MessageQueues/MessageQueuesClient.cs" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/InterProcessComms/MessageQueues/MessageQueuesClient.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.InterProcessComms\&.MessageQueues\&.MessageQueueClient\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.InterProcessComms\fP"
.br
.RI "Gist from: https://weblogs.asp.net/ricardoperes/local-machine-interprocess-communication-with-netD "
.ti -1c
.RI "namespace \fBJBToolkit\&.InterProcessComms\&.MessageQueues\fP"
.br
.RI "\fBWindows\fP has included a message queues implementation for a long time, something that is often forgotten by developers\&. If you don’t have it installed – you can check if the Message Queuing service exists – you can install it through Programs and Features – Turn \fBWindows\fP features on and off on the \fBControl\fP Panel\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
