.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/XmlDoc/Converters/OfficeHtmlPdfImageConverter.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/XmlDoc/Converters/OfficeHtmlPdfImageConverter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.XmlDoc\&.Converters\&.OfficeHtmlPdfImageConverter\fP"
.br
.RI "Uses a decent 3rd party command line tool to perform MS Office / PDF / Html conversions\&. "
.ti -1c
.RI "class \fBJBToolkit\&.XmlDoc\&.Converters\&.OfficeHtmlPdfImageConverter\&.AdditionalOptions\fP"
.br
.RI "Additional input options "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\&.Converters\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
