.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Windows/ConsoleHelper/Options.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/Windows/ConsoleHelper/Options.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.StringCoda\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionValueCollection\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionContext\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.Option\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.ArgumentSource\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.ResponseFileSource\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionException\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionSet\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionSet\&.Category\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.Command\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.CommandOption\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.HelpOption\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.CommandOptionSet\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.CommandSet\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.ConsoleHelper\&.HelpCommand\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Windows\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Windows\&.ConsoleHelper\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBMessageLocalizerConverter\fP = System\&.Converter< string, string >"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionValueType\fP { \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionValueType\&.None\fP, \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionValueType\&.Optional\fP, \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionValueType\&.Required\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBJBToolkit\&.Windows\&.ConsoleHelper\&.OptionAction< TKey, TValue >\fP (TKey key, TValue value)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBMessageLocalizerConverter\fP =  System\&.Converter<string, string>"

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
