.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/ConsoleHelper/Options.cs" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/ConsoleHelper/Options.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.StringCoda\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionValueCollection\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionContext\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.Option\fP"
.br
.RI "User Guide: http://docs.go-mono.com/index.aspx?link=T:Mono.Options.OptionSet "
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.ArgumentSource\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.ResponseFileSource\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionException\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionSet\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionSet\&.Category\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.Command\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.CommandOption\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.HelpOption\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.CommandOptionSet\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.CommandSet\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ConsoleHelper\&.Options\&.HelpCommand\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.ConsoleHelper\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.ConsoleHelper\&.Options\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBMessageLocalizerConverter\fP = System\&.Converter< string, string >"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionValueType\fP { \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionValueType\&.None\fP, \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionValueType\&.Optional\fP, \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionValueType\&.Required\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBJBToolkit\&.ConsoleHelper\&.Options\&.OptionAction< TKey, TValue >\fP (TKey key, TValue value)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBMessageLocalizerConverter\fP =  System\&.Converter<string, string>"

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
