.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/XmlDoc/Parser.cs" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JBToolkit/XmlDoc/Parser.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.XmlDoc\&.Parser\fP"
.br
.RI "Parses and returns the text an MS Office document (docx, xlsx, msg, eml, pptx, vsdx, pub), PDF, or Image (using OCR) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
