.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/PdfDoc/Converters/PdfConverter_DocToPdf.cs" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/PdfDoc/Converters/PdfConverter_DocToPdf.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.PdfDoc\&.PdfConverter\fP"
.br
.RI "Methods to convert Docx to PDF through M-Files\&. I've done it this way as it's costs a tonne for a docx to pdf converter license with the likes of Aspose, Spire, ABCpdf etc and M-Files is already using Aspose so just utilise that\&. The process involves uploading a file to M-Files, converting it to a PDF there, then downloading it as PDF and finally deleting (destroying) the file in the M-Files vault "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.PdfDoc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
