.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/XmlDoc/MailMerge/ReAlMailMerge.cs" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/XmlDoc/MailMerge/ReAlMailMerge.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.XmlDoc\&.MailMerge\&.ReAlMailMerge\fP"
.br
.RI "Mail merging using a 3rd party command line tool\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\&.MailMerge\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
