.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Extensions/SourceCodeFormatter.cs" 3 "Tue Sep 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Extensions/SourceCodeFormatter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\fP"
.br
.RI "Use to format json without the use of serialisation, in order to try and ignore any syntax errors "
.ti -1c
.RI "class \fBJBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.StringWalker\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.Extensions\&.SourceCode\&.SourceCodeFormatter\&.LenientJsonFormatter\&.IndentWriter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Extensions\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Extensions\&.SourceCode\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
