.TH "System.TryWrapper< T >" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.TryWrapper< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystem\&.CatchWrapper< T >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator T\fP (\fBTryWrapper\fP< T > wrapper)"
.br
.ti -1c
.RI "static implicit \fBoperator Exception\fP (\fBTryWrapper\fP< T > wrapper)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static implicit \fBSystem\&.TryWrapper\fP< T >\&.operator \fBException\fP (\fBTryWrapper\fP< T > wrapper)\fC [static]\fP"

.SS "static implicit \fBSystem\&.TryWrapper\fP< T >\&.operator T (\fBTryWrapper\fP< T > wrapper)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
