.TH "System.Web.Mvc" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Web.Mvc
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAttachmentAttribute\fP"
.br
.ti -1c
.RI "class \fBHtmlExtensions\fP"
.br
.RI "Class adds extension objects to the HTML options (i\&.e\&. @Html\&.LabelFor) within views\&. For example the @Html\&.FileFor is fully built here and includes the incorporation of custom validators\&. It's fully re-usable "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
