.TH "System.CatchWrapper< T >" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.CatchWrapper< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystem\&.TryWrapper< T >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
