.TH "System.Drawing.Html.CssConstants" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Drawing.Html.CssConstants \- String constants to avoid typing errors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBAbsolute\fP = 'absolute'"
.br
.ti -1c
.RI "const string \fBAuto\fP = 'auto'"
.br
.ti -1c
.RI "const string \fBBaseline\fP = 'baseline'"
.br
.ti -1c
.RI "const string \fBBlink\fP = 'blink'"
.br
.ti -1c
.RI "const string \fBBlock\fP = 'block'"
.br
.ti -1c
.RI "const string \fBBold\fP = 'bold'"
.br
.ti -1c
.RI "const string \fBBolder\fP = 'bolder'"
.br
.ti -1c
.RI "const string \fBBottom\fP = 'bottom'"
.br
.ti -1c
.RI "const string \fBCenter\fP = 'center'"
.br
.ti -1c
.RI "const string \fBCollapse\fP = 'collapse'"
.br
.ti -1c
.RI "const string \fBCursive\fP = 'cursive'"
.br
.ti -1c
.RI "const string \fBDecimal\fP = 'decimal'"
.br
.ti -1c
.RI "const string \fBFantasy\fP = 'fantasy'"
.br
.ti -1c
.RI "const string \fBHide\fP = 'hide'"
.br
.ti -1c
.RI "const string \fBInherit\fP = 'inherit'"
.br
.ti -1c
.RI "const string \fBInline\fP = 'inline'"
.br
.ti -1c
.RI "const string \fBInlineTable\fP = 'inline\-table'"
.br
.ti -1c
.RI "const string \fBInset\fP = 'inset'"
.br
.ti -1c
.RI "const string \fBItalic\fP = 'italic'"
.br
.ti -1c
.RI "const string \fBJustify\fP = 'justify'"
.br
.ti -1c
.RI "const string \fBLarge\fP = 'large'"
.br
.ti -1c
.RI "const string \fBLarger\fP = 'larger'"
.br
.ti -1c
.RI "const string \fBLeft\fP = 'left'"
.br
.ti -1c
.RI "const string \fBLighter\fP = 'lighter'"
.br
.ti -1c
.RI "const string \fBLineThrough\fP = 'line\-through'"
.br
.ti -1c
.RI "const string \fBListItem\fP = 'list\-item'"
.br
.ti -1c
.RI "const string \fBLtr\fP = 'ltr'"
.br
.ti -1c
.RI "const string \fBMedium\fP = 'medium'"
.br
.ti -1c
.RI "const string \fBMiddle\fP = 'middle'"
.br
.ti -1c
.RI "const string \fBMonospace\fP = 'monospace'"
.br
.ti -1c
.RI "const string \fBNone\fP = 'none'"
.br
.ti -1c
.RI "const string \fBNormal\fP = 'normal'"
.br
.ti -1c
.RI "const string \fBNowrap\fP = 'nowrap'"
.br
.ti -1c
.RI "const string \fBOblique\fP = 'oblique'"
.br
.ti -1c
.RI "const string \fBOutset\fP = 'outset'"
.br
.ti -1c
.RI "const string \fBOverline\fP = 'overline'"
.br
.ti -1c
.RI "const string \fBPre\fP = 'pre'"
.br
.ti -1c
.RI "const string \fBPreWrap\fP = 'pre\-wrap'"
.br
.ti -1c
.RI "const string \fBPreLine\fP = 'pre\-line'"
.br
.ti -1c
.RI "const string \fBRight\fP = 'right'"
.br
.ti -1c
.RI "const string \fBRtl\fP = 'rtl'"
.br
.ti -1c
.RI "const string \fBSansSerif\fP = 'sans\-serif'"
.br
.ti -1c
.RI "const string \fBSerif\fP = 'serif'"
.br
.ti -1c
.RI "const string \fBShow\fP = 'show'"
.br
.ti -1c
.RI "const string \fBSmall\fP = 'small'"
.br
.ti -1c
.RI "const string \fBSmaller\fP = 'smaller'"
.br
.ti -1c
.RI "const string \fBSolid\fP = 'solid'"
.br
.ti -1c
.RI "const string \fBSub\fP = 'sub'"
.br
.ti -1c
.RI "const string \fBSuper\fP = 'super'"
.br
.ti -1c
.RI "const string \fBTable\fP = 'table'"
.br
.ti -1c
.RI "const string \fBTableRow\fP = 'table\-row'"
.br
.ti -1c
.RI "const string \fBTableRowGroup\fP = 'table\-row\-group'"
.br
.ti -1c
.RI "const string \fBTableHeaderGroup\fP = 'table\-header\-group'"
.br
.ti -1c
.RI "const string \fBTableFooterGroup\fP = 'table\-footer\-group'"
.br
.ti -1c
.RI "const string \fBTableColumn\fP = 'table\-column'"
.br
.ti -1c
.RI "const string \fBTableColumnGroup\fP = 'table\-column\-group'"
.br
.ti -1c
.RI "const string \fBTableCell\fP = 'table\-cell'"
.br
.ti -1c
.RI "const string \fBTableCaption\fP = 'table\-caption'"
.br
.ti -1c
.RI "const string \fBTextBottom\fP = 'text\-bottom'"
.br
.ti -1c
.RI "const string \fBTextTop\fP = 'text\-top'"
.br
.ti -1c
.RI "const string \fBThin\fP = 'thin'"
.br
.ti -1c
.RI "const string \fBThick\fP = 'thick'"
.br
.ti -1c
.RI "const string \fBTop\fP = 'top'"
.br
.ti -1c
.RI "const string \fBUnderline\fP = 'underline'"
.br
.ti -1c
.RI "const string \fBXLarge\fP = 'x\-large'"
.br
.ti -1c
.RI "const string \fBXSmall\fP = 'x\-small'"
.br
.ti -1c
.RI "const string \fBXXLarge\fP = 'xx\-large'"
.br
.ti -1c
.RI "const string \fBXXSmall\fP = 'xx\-small'"
.br
.ti -1c
.RI "const string \fBCm\fP = 'cm'"
.br
.RI "Centimeters "
.ti -1c
.RI "const string \fBMm\fP = 'mm'"
.br
.RI "Milimeters "
.ti -1c
.RI "const string \fBPx\fP = 'px'"
.br
.RI "Pixels "
.ti -1c
.RI "const string \fBIn\fP = 'in'"
.br
.RI "Inches "
.ti -1c
.RI "const string \fBEm\fP = 'em'"
.br
.RI "Em - The font size of the relevant font "
.ti -1c
.RI "const string \fBEx\fP = 'ex'"
.br
.RI "The 'x-height' of the relevan font "
.ti -1c
.RI "const string \fBPt\fP = 'pt'"
.br
.RI "Points "
.ti -1c
.RI "const string \fBPc\fP = 'pc'"
.br
.RI "Picas "
.ti -1c
.RI "const string \fBMaroon\fP = 'maroon'"
.br
.ti -1c
.RI "const string \fBRed\fP = 'red'"
.br
.ti -1c
.RI "const string \fBOrange\fP = 'orange'"
.br
.ti -1c
.RI "const string \fBYellow\fP = 'yellow'"
.br
.ti -1c
.RI "const string \fBOlive\fP = 'olive'"
.br
.ti -1c
.RI "const string \fBFuchsia\fP = 'fuchsia'"
.br
.ti -1c
.RI "const string \fBLime\fP = 'lime'"
.br
.ti -1c
.RI "const string \fBWhite\fP = 'white'"
.br
.ti -1c
.RI "const string \fBGreen\fP = 'green'"
.br
.ti -1c
.RI "const string \fBNavy\fP = 'navy'"
.br
.ti -1c
.RI "const string \fBBlue\fP = 'blue'"
.br
.ti -1c
.RI "const string \fBAqua\fP = 'aqua'"
.br
.ti -1c
.RI "const string \fBTeal\fP = 'teal'"
.br
.ti -1c
.RI "const string \fBBlack\fP = 'black'"
.br
.ti -1c
.RI "const string \fBSilver\fP = 'silver'"
.br
.ti -1c
.RI "const string \fBGray\fP = 'gray'"
.br
.ti -1c
.RI "const string \fBPurple\fP = 'purple'"
.br
.in -1c
.SH "Detailed Description"
.PP 
String constants to avoid typing errors\&. 


.SH "Member Data Documentation"
.PP 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Absolute = 'absolute'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Aqua = 'aqua'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Auto = 'auto'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Baseline = 'baseline'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Black = 'black'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Blink = 'blink'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Block = 'block'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Blue = 'blue'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Bold = 'bold'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Bolder = 'bolder'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Bottom = 'bottom'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Center = 'center'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Cm = 'cm'\fC [static]\fP"

.PP
Centimeters 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Collapse = 'collapse'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Cursive = 'cursive'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Decimal = 'decimal'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Em = 'em'\fC [static]\fP"

.PP
Em - The font size of the relevant font 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Ex = 'ex'\fC [static]\fP"

.PP
The 'x-height' of the relevan font 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Fantasy = 'fantasy'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Fuchsia = 'fuchsia'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Gray = 'gray'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Green = 'green'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Hide = 'hide'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.In = 'in'\fC [static]\fP"

.PP
Inches 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Inherit = 'inherit'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Inline = 'inline'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.InlineTable = 'inline\-table'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Inset = 'inset'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Italic = 'italic'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Justify = 'justify'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Large = 'large'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Larger = 'larger'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Left = 'left'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Lighter = 'lighter'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Lime = 'lime'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.LineThrough = 'line\-through'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.ListItem = 'list\-item'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Ltr = 'ltr'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Maroon = 'maroon'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Medium = 'medium'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Middle = 'middle'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Mm = 'mm'\fC [static]\fP"

.PP
Milimeters 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Monospace = 'monospace'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Navy = 'navy'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.None = 'none'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Normal = 'normal'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Nowrap = 'nowrap'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Oblique = 'oblique'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Olive = 'olive'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Orange = 'orange'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Outset = 'outset'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Overline = 'overline'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Pc = 'pc'\fC [static]\fP"

.PP
Picas 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Pre = 'pre'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.PreLine = 'pre\-line'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.PreWrap = 'pre\-wrap'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Pt = 'pt'\fC [static]\fP"

.PP
Points 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Purple = 'purple'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Px = 'px'\fC [static]\fP"

.PP
Pixels 
.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Red = 'red'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Right = 'right'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Rtl = 'rtl'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.SansSerif = 'sans\-serif'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Serif = 'serif'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Show = 'show'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Silver = 'silver'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Small = 'small'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Smaller = 'smaller'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Solid = 'solid'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Sub = 'sub'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Super = 'super'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Table = 'table'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TableCaption = 'table\-caption'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TableCell = 'table\-cell'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TableColumn = 'table\-column'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TableColumnGroup = 'table\-column\-group'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TableFooterGroup = 'table\-footer\-group'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TableHeaderGroup = 'table\-header\-group'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TableRow = 'table\-row'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TableRowGroup = 'table\-row\-group'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Teal = 'teal'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TextBottom = 'text\-bottom'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.TextTop = 'text\-top'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Thick = 'thick'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Thin = 'thin'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Top = 'top'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Underline = 'underline'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.White = 'white'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.XLarge = 'x\-large'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.XSmall = 'x\-small'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.XXLarge = 'xx\-large'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.XXSmall = 'xx\-small'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.CssConstants\&.Yellow = 'yellow'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
