.TH "System.Drawing.Html.CssTable.SpacingBox" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Drawing.Html.CssTable.SpacingBox \- Used to make space on vertical cell combination  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystem\&.Drawing\&.Html\&.CssBox\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpacingBox\fP (\fBCssBox\fP tableBox, ref \fBCssBox\fP extendedBox, int startRow)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBCssBox\fP \fBExtendedBox\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBStartRow\fP\fC [get]\fP"
.br
.RI "Gets the index of the row where box starts "
.ti -1c
.RI "int \fBEndRow\fP\fC [get]\fP"
.br
.RI "Gets the index of the row where box ends "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Used to make space on vertical cell combination 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "System\&.Drawing\&.Html\&.CssTable\&.SpacingBox\&.SpacingBox (\fBCssBox\fP tableBox, ref \fBCssBox\fP extendedBox, int startRow)"

.SH "Member Data Documentation"
.PP 
.SS "readonly \fBCssBox\fP System\&.Drawing\&.Html\&.CssTable\&.SpacingBox\&.ExtendedBox"

.SH "Property Documentation"
.PP 
.SS "int System\&.Drawing\&.Html\&.CssTable\&.SpacingBox\&.EndRow\fC [get]\fP"

.PP
Gets the index of the row where box ends 
.SS "int System\&.Drawing\&.Html\&.CssTable\&.SpacingBox\&.StartRow\fC [get]\fP"

.PP
Gets the index of the row where box starts 

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
