.TH "System.Drawing.Html.CssAnonymousSpaceBlockBox" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Drawing.Html.CssAnonymousSpaceBlockBox \- Represents an AnonymousBlockBox which contains only blank spaces  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystem\&.Drawing\&.Html\&.CssAnonymousBlockBox\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCssAnonymousSpaceBlockBox\fP (\fBCssBox\fP parent)"
.br
.ti -1c
.RI "\fBCssAnonymousSpaceBlockBox\fP (\fBCssBox\fP parent, \fBCssBox\fP insertBefore)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents an AnonymousBlockBox which contains only blank spaces 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "System\&.Drawing\&.Html\&.CssAnonymousSpaceBlockBox\&.CssAnonymousSpaceBlockBox (\fBCssBox\fP parent)"

.SS "System\&.Drawing\&.Html\&.CssAnonymousSpaceBlockBox\&.CssAnonymousSpaceBlockBox (\fBCssBox\fP parent, \fBCssBox\fP insertBefore)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
