.TH "System.Drawing.Html.CssRectangle" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Drawing.Html.CssRectangle
.SH SYNOPSIS
.br
.PP
.PP
Inherited by System\&.Drawing\&.Html\&.CssBoxWord\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBLeft\fP\fC [get, set]\fP"
.br
.RI "Left of the rectangle "
.ti -1c
.RI "float \fBTop\fP\fC [get, set]\fP"
.br
.RI "Top of the rectangle "
.ti -1c
.RI "float \fBWidth\fP\fC [get, set]\fP"
.br
.RI "Width of the rectangle "
.ti -1c
.RI "float \fBHeight\fP\fC [get, set]\fP"
.br
.RI "Height of the rectangle "
.ti -1c
.RI "float \fBRight\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the right of the rectangle\&. When setting, it only affects the Width of the rectangle\&. "
.ti -1c
.RI "float \fBBottom\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the bottom of the rectangle\&. When setting, it only affects the Height of the rectangle\&. "
.ti -1c
.RI "RectangleF \fBBounds\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the bounds of the rectangle "
.ti -1c
.RI "PointF \fBLocation\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the location of the rectangle "
.ti -1c
.RI "SizeF \fBSize\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the size of the rectangle "
.in -1c
.SH "Property Documentation"
.PP 
.SS "float System\&.Drawing\&.Html\&.CssRectangle\&.Bottom\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the bottom of the rectangle\&. When setting, it only affects the Height of the rectangle\&. 
.SS "RectangleF System\&.Drawing\&.Html\&.CssRectangle\&.Bounds\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the bounds of the rectangle 
.SS "float System\&.Drawing\&.Html\&.CssRectangle\&.Height\fC [get]\fP, \fC [set]\fP"

.PP
Height of the rectangle 
.SS "float System\&.Drawing\&.Html\&.CssRectangle\&.Left\fC [get]\fP, \fC [set]\fP"

.PP
Left of the rectangle 
.SS "PointF System\&.Drawing\&.Html\&.CssRectangle\&.Location\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the location of the rectangle 
.SS "float System\&.Drawing\&.Html\&.CssRectangle\&.Right\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the right of the rectangle\&. When setting, it only affects the Width of the rectangle\&. 
.SS "SizeF System\&.Drawing\&.Html\&.CssRectangle\&.Size\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the size of the rectangle 
.SS "float System\&.Drawing\&.Html\&.CssRectangle\&.Top\fC [get]\fP, \fC [set]\fP"

.PP
Top of the rectangle 
.SS "float System\&.Drawing\&.Html\&.CssRectangle\&.Width\fC [get]\fP, \fC [set]\fP"

.PP
Width of the rectangle 

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
