.TH "System.Drawing.Html.HtmlConstants" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Drawing.Html.HtmlConstants \- Defines HTML strings  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBA\fP = 'A'"
.br
.ti -1c
.RI "const string \fBABBR\fP = 'ABBR'"
.br
.ti -1c
.RI "const string \fBACRONYM\fP = 'ACRONYM'"
.br
.ti -1c
.RI "const string \fBADDRESS\fP = 'ADDRESS'"
.br
.ti -1c
.RI "const string \fBAPPLET\fP = 'APPLET'"
.br
.ti -1c
.RI "const string \fBAREA\fP = 'AREA'"
.br
.ti -1c
.RI "const string \fBB\fP = 'B'"
.br
.ti -1c
.RI "const string \fBBASE\fP = 'BASE'"
.br
.ti -1c
.RI "const string \fBBASEFONT\fP = 'BASEFONT'"
.br
.ti -1c
.RI "const string \fBBDO\fP = 'BDO'"
.br
.ti -1c
.RI "const string \fBBIG\fP = 'BIG'"
.br
.ti -1c
.RI "const string \fBBLOCKQUOTE\fP = 'BLOCKQUOTE'"
.br
.ti -1c
.RI "const string \fBBODY\fP = 'BODY'"
.br
.ti -1c
.RI "const string \fBBR\fP = 'BR'"
.br
.ti -1c
.RI "const string \fBBUTTON\fP = 'BUTTON'"
.br
.ti -1c
.RI "const string \fBCAPTION\fP = 'CAPTION'"
.br
.ti -1c
.RI "const string \fBCENTER\fP = 'CENTER'"
.br
.ti -1c
.RI "const string \fBCITE\fP = 'CITE'"
.br
.ti -1c
.RI "const string \fBCODE\fP = 'CODE'"
.br
.ti -1c
.RI "const string \fBCOL\fP = 'COL'"
.br
.ti -1c
.RI "const string \fBCOLGROUP\fP = 'COLGROUP'"
.br
.ti -1c
.RI "const string \fBDD\fP = 'DD'"
.br
.ti -1c
.RI "const string \fBDEL\fP = 'DEL'"
.br
.ti -1c
.RI "const string \fBDFN\fP = 'DFN'"
.br
.ti -1c
.RI "const string \fBDIR\fP = 'DIR'"
.br
.ti -1c
.RI "const string \fBDIV\fP = 'DIV'"
.br
.ti -1c
.RI "const string \fBDL\fP = 'DL'"
.br
.ti -1c
.RI "const string \fBDT\fP = 'DT'"
.br
.ti -1c
.RI "const string \fBEM\fP = 'EM'"
.br
.ti -1c
.RI "const string \fBFIELDSET\fP = 'FIELDSET'"
.br
.ti -1c
.RI "const string \fBFONT\fP = 'FONT'"
.br
.ti -1c
.RI "const string \fBFORM\fP = 'FORM'"
.br
.ti -1c
.RI "const string \fBFRAME\fP = 'FRAME'"
.br
.ti -1c
.RI "const string \fBFRAMESET\fP = 'FRAMESET'"
.br
.ti -1c
.RI "const string \fBH1\fP = 'H1'"
.br
.ti -1c
.RI "const string \fBH2\fP = 'H2'"
.br
.ti -1c
.RI "const string \fBH3\fP = 'H3'"
.br
.ti -1c
.RI "const string \fBH4\fP = 'H4'"
.br
.ti -1c
.RI "const string \fBH5\fP = 'H5'"
.br
.ti -1c
.RI "const string \fBH6\fP = 'H6'"
.br
.ti -1c
.RI "const string \fBHEAD\fP = 'HEAD'"
.br
.ti -1c
.RI "const string \fBHR\fP = 'HR'"
.br
.ti -1c
.RI "const string \fBHTML\fP = 'HTML'"
.br
.ti -1c
.RI "const string \fBI\fP = 'I'"
.br
.ti -1c
.RI "const string \fBIFRAME\fP = 'IFRAME'"
.br
.ti -1c
.RI "const string \fBIMG\fP = 'IMG'"
.br
.ti -1c
.RI "const string \fBINPUT\fP = 'INPUT'"
.br
.ti -1c
.RI "const string \fBINS\fP = 'INS'"
.br
.ti -1c
.RI "const string \fBISINDEX\fP = 'ISINDEX'"
.br
.ti -1c
.RI "const string \fBKBD\fP = 'KBD'"
.br
.ti -1c
.RI "const string \fBLABEL\fP = 'LABEL'"
.br
.ti -1c
.RI "const string \fBLEGEND\fP = 'LEGEND'"
.br
.ti -1c
.RI "const string \fBLI\fP = 'LI'"
.br
.ti -1c
.RI "const string \fBLINK\fP = 'LINK'"
.br
.ti -1c
.RI "const string \fBMAP\fP = 'MAP'"
.br
.ti -1c
.RI "const string \fBMENU\fP = 'MENU'"
.br
.ti -1c
.RI "const string \fBMETA\fP = 'META'"
.br
.ti -1c
.RI "const string \fBNOFRAMES\fP = 'NOFRAMES'"
.br
.ti -1c
.RI "const string \fBNOSCRIPT\fP = 'NOSCRIPT'"
.br
.ti -1c
.RI "const string \fBOBJECT\fP = 'OBJECT'"
.br
.ti -1c
.RI "const string \fBOL\fP = 'OL'"
.br
.ti -1c
.RI "const string \fBOPTGROUP\fP = 'OPTGROUP'"
.br
.ti -1c
.RI "const string \fBOPTION\fP = 'OPTION'"
.br
.ti -1c
.RI "const string \fBP\fP = 'P'"
.br
.ti -1c
.RI "const string \fBPARAM\fP = 'PARAM'"
.br
.ti -1c
.RI "const string \fBPRE\fP = 'PRE'"
.br
.ti -1c
.RI "const string \fBQ\fP = 'Q'"
.br
.ti -1c
.RI "const string \fBS\fP = 'S'"
.br
.ti -1c
.RI "const string \fBSAMP\fP = 'SAMP'"
.br
.ti -1c
.RI "const string \fBSCRIPT\fP = 'SCRIPT'"
.br
.ti -1c
.RI "const string \fBSELECT\fP = 'SELECT'"
.br
.ti -1c
.RI "const string \fBSMALL\fP = 'SMALL'"
.br
.ti -1c
.RI "const string \fBSPAN\fP = 'SPAN'"
.br
.ti -1c
.RI "const string \fBSTRIKE\fP = 'STRIKE'"
.br
.ti -1c
.RI "const string \fBSTRONG\fP = 'STRONG'"
.br
.ti -1c
.RI "const string \fBSTYLE\fP = 'STYLE'"
.br
.ti -1c
.RI "const string \fBSUB\fP = 'SUB'"
.br
.ti -1c
.RI "const string \fBSUP\fP = 'SUP'"
.br
.ti -1c
.RI "const string \fBTABLE\fP = 'TABLE'"
.br
.ti -1c
.RI "const string \fBTBODY\fP = 'TBODY'"
.br
.ti -1c
.RI "const string \fBTD\fP = 'TD'"
.br
.ti -1c
.RI "const string \fBTEXTAREA\fP = 'TEXTAREA'"
.br
.ti -1c
.RI "const string \fBTFOOT\fP = 'TFOOT'"
.br
.ti -1c
.RI "const string \fBTH\fP = 'TH'"
.br
.ti -1c
.RI "const string \fBTHEAD\fP = 'THEAD'"
.br
.ti -1c
.RI "const string \fBTITLE\fP = 'TITLE'"
.br
.ti -1c
.RI "const string \fBTR\fP = 'TR'"
.br
.ti -1c
.RI "const string \fBTT\fP = 'TT'"
.br
.ti -1c
.RI "const string \fBU\fP = 'U'"
.br
.ti -1c
.RI "const string \fBUL\fP = 'UL'"
.br
.ti -1c
.RI "const string \fBVAR\fP = 'VAR'"
.br
.ti -1c
.RI "const string \fBabbr\fP = 'abbr'"
.br
.ti -1c
.RI "const string \fBaccept\fP = 'accept'"
.br
.ti -1c
.RI "const string \fBaccesskey\fP = 'accesskey'"
.br
.ti -1c
.RI "const string \fBaction\fP = 'action'"
.br
.ti -1c
.RI "const string \fBalign\fP = 'align'"
.br
.ti -1c
.RI "const string \fBalink\fP = 'alink'"
.br
.ti -1c
.RI "const string \fBalt\fP = 'alt'"
.br
.ti -1c
.RI "const string \fBarchive\fP = 'archive'"
.br
.ti -1c
.RI "const string \fBaxis\fP = 'axis'"
.br
.ti -1c
.RI "const string \fBbackground\fP = 'background'"
.br
.ti -1c
.RI "const string \fBbgcolor\fP = 'bgcolor'"
.br
.ti -1c
.RI "const string \fBborder\fP = 'border'"
.br
.ti -1c
.RI "const string \fBbordercolor\fP = 'bordercolor'"
.br
.ti -1c
.RI "const string \fBcellpadding\fP = 'cellpadding'"
.br
.ti -1c
.RI "const string \fBcellspacing\fP = 'cellspacing'"
.br
.ti -1c
.RI "const string \fBchar_\fP = 'char'"
.br
.ti -1c
.RI "const string \fBcharoff\fP = 'charoff'"
.br
.ti -1c
.RI "const string \fBcharset\fP = 'charset'"
.br
.ti -1c
.RI "const string \fBchecked_\fP = 'checked'"
.br
.ti -1c
.RI "const string \fBcite\fP = 'cite'"
.br
.ti -1c
.RI "const string \fBclass_\fP = 'class'"
.br
.ti -1c
.RI "const string \fBclassid\fP = 'classid'"
.br
.ti -1c
.RI "const string \fBclear\fP = 'clear'"
.br
.ti -1c
.RI "const string \fBcode\fP = 'code'"
.br
.ti -1c
.RI "const string \fBcodebase\fP = 'codebase'"
.br
.ti -1c
.RI "const string \fBcodetype\fP = 'codetype'"
.br
.ti -1c
.RI "const string \fBcolor\fP = 'color'"
.br
.ti -1c
.RI "const string \fBcols\fP = 'cols'"
.br
.ti -1c
.RI "const string \fBcolspan\fP = 'colspan'"
.br
.ti -1c
.RI "const string \fBcompact\fP = 'compact'"
.br
.ti -1c
.RI "const string \fBcontent\fP = 'content'"
.br
.ti -1c
.RI "const string \fBcoords\fP = 'coords'"
.br
.ti -1c
.RI "const string \fBdata\fP = 'data'"
.br
.ti -1c
.RI "const string \fBdatetime\fP = 'datetime'"
.br
.ti -1c
.RI "const string \fBdeclare\fP = 'declare'"
.br
.ti -1c
.RI "const string \fBdefer\fP = 'defer'"
.br
.ti -1c
.RI "const string \fBdir\fP = 'dir'"
.br
.ti -1c
.RI "const string \fBdisabled\fP = 'disabled'"
.br
.ti -1c
.RI "const string \fBenctype\fP = 'enctype'"
.br
.ti -1c
.RI "const string \fBface\fP = 'face'"
.br
.ti -1c
.RI "const string \fBfor_\fP = 'for'"
.br
.ti -1c
.RI "const string \fBframe\fP = 'frame'"
.br
.ti -1c
.RI "const string \fBframeborder\fP = 'frameborder'"
.br
.ti -1c
.RI "const string \fBheaders\fP = 'headers'"
.br
.ti -1c
.RI "const string \fBheight\fP = 'height'"
.br
.ti -1c
.RI "const string \fBhref\fP = 'href'"
.br
.ti -1c
.RI "const string \fBhreflang\fP = 'hreflang'"
.br
.ti -1c
.RI "const string \fBhspace\fP = 'hspace'"
.br
.ti -1c
.RI "const string \fBhttp_equiv\fP = 'http\-equiv'"
.br
.ti -1c
.RI "const string \fBid\fP = 'id'"
.br
.ti -1c
.RI "const string \fBismap\fP = 'ismap'"
.br
.ti -1c
.RI "const string \fBlabel\fP = 'label'"
.br
.ti -1c
.RI "const string \fBlang\fP = 'lang'"
.br
.ti -1c
.RI "const string \fBlanguage\fP = 'language'"
.br
.ti -1c
.RI "const string \fBlink\fP = 'link'"
.br
.ti -1c
.RI "const string \fBlongdesc\fP = 'longdesc'"
.br
.ti -1c
.RI "const string \fBmarginheight\fP = 'marginheight'"
.br
.ti -1c
.RI "const string \fBmarginwidth\fP = 'marginwidth'"
.br
.ti -1c
.RI "const string \fBmaxlength\fP = 'maxlength'"
.br
.ti -1c
.RI "const string \fBmedia\fP = 'media'"
.br
.ti -1c
.RI "const string \fBmethod\fP = 'method'"
.br
.ti -1c
.RI "const string \fBmultiple\fP = 'multiple'"
.br
.ti -1c
.RI "const string \fBname\fP = 'name'"
.br
.ti -1c
.RI "const string \fBnohref\fP = 'nohref'"
.br
.ti -1c
.RI "const string \fBnoresize\fP = 'noresize'"
.br
.ti -1c
.RI "const string \fBnoshade\fP = 'noshade'"
.br
.ti -1c
.RI "const string \fBnowrap\fP = 'nowrap'"
.br
.ti -1c
.RI "const string \fBobject_\fP = 'object'"
.br
.ti -1c
.RI "const string \fBonblur\fP = 'onblur'"
.br
.ti -1c
.RI "const string \fBonchange\fP = 'onchange'"
.br
.ti -1c
.RI "const string \fBonclick\fP = 'onclick'"
.br
.ti -1c
.RI "const string \fBondblclick\fP = 'ondblclick'"
.br
.ti -1c
.RI "const string \fBonfocus\fP = 'onfocus'"
.br
.ti -1c
.RI "const string \fBonkeydown\fP = 'onkeydown'"
.br
.ti -1c
.RI "const string \fBonkeypress\fP = 'onkeypress'"
.br
.ti -1c
.RI "const string \fBonkeyup\fP = 'onkeyup'"
.br
.ti -1c
.RI "const string \fBonload\fP = 'onload'"
.br
.ti -1c
.RI "const string \fBonmousedown\fP = 'onmousedown'"
.br
.ti -1c
.RI "const string \fBonmousemove\fP = 'onmousemove'"
.br
.ti -1c
.RI "const string \fBonmouseout\fP = 'onmouseout'"
.br
.ti -1c
.RI "const string \fBonmouseover\fP = 'onmouseover'"
.br
.ti -1c
.RI "const string \fBonmouseup\fP = 'onmouseup'"
.br
.ti -1c
.RI "const string \fBonreset\fP = 'onreset'"
.br
.ti -1c
.RI "const string \fBonselect\fP = 'onselect'"
.br
.ti -1c
.RI "const string \fBonsubmit\fP = 'onsubmit'"
.br
.ti -1c
.RI "const string \fBonunload\fP = 'onunload'"
.br
.ti -1c
.RI "const string \fBprofile\fP = 'profile'"
.br
.ti -1c
.RI "const string \fBprompt\fP = 'prompt'"
.br
.ti -1c
.RI "const string \fBreadonly_\fP = 'readonly'"
.br
.ti -1c
.RI "const string \fBrel\fP = 'rel'"
.br
.ti -1c
.RI "const string \fBrev\fP = 'rev'"
.br
.ti -1c
.RI "const string \fBrows\fP = 'rows'"
.br
.ti -1c
.RI "const string \fBrowspan\fP = 'rowspan'"
.br
.ti -1c
.RI "const string \fBrules\fP = 'rules'"
.br
.ti -1c
.RI "const string \fBscheme\fP = 'scheme'"
.br
.ti -1c
.RI "const string \fBscope\fP = 'scope'"
.br
.ti -1c
.RI "const string \fBscrolling\fP = 'scrolling'"
.br
.ti -1c
.RI "const string \fBselected\fP = 'selected'"
.br
.ti -1c
.RI "const string \fBshape\fP = 'shape'"
.br
.ti -1c
.RI "const string \fBsize\fP = 'size'"
.br
.ti -1c
.RI "const string \fBspan\fP = 'span'"
.br
.ti -1c
.RI "const string \fBsrc\fP = 'src'"
.br
.ti -1c
.RI "const string \fBstandby\fP = 'standby'"
.br
.ti -1c
.RI "const string \fBstart\fP = 'start'"
.br
.ti -1c
.RI "const string \fBstyle\fP = 'style'"
.br
.ti -1c
.RI "const string \fBsummary\fP = 'summary'"
.br
.ti -1c
.RI "const string \fBtabindex\fP = 'tabindex'"
.br
.ti -1c
.RI "const string \fBtarget\fP = 'target'"
.br
.ti -1c
.RI "const string \fBtext\fP = 'text'"
.br
.ti -1c
.RI "const string \fBtitle\fP = 'title'"
.br
.ti -1c
.RI "const string \fBtype\fP = 'type'"
.br
.ti -1c
.RI "const string \fBusemap\fP = 'usemap'"
.br
.ti -1c
.RI "const string \fBvalign\fP = 'valign'"
.br
.ti -1c
.RI "const string \fBvalue\fP = 'value'"
.br
.ti -1c
.RI "const string interface \fBvaluetype\fP"
.br
.ti -1c
.RI "const string \fBversion\fP = 'version'"
.br
.ti -1c
.RI "const string \fBvlink\fP = 'vlink'"
.br
.ti -1c
.RI "const string \fBvspace\fP = 'vspace'"
.br
.ti -1c
.RI "const string \fBwidth\fP = 'width'"
.br
.ti -1c
.RI "const string \fBleft\fP = 'left'"
.br
.ti -1c
.RI "const string \fBright\fP = 'right'"
.br
.ti -1c
.RI "const string \fBtop\fP = 'top'"
.br
.ti -1c
.RI "const string \fBcenter\fP = 'center'"
.br
.ti -1c
.RI "const string \fBmiddle\fP = 'middle'"
.br
.ti -1c
.RI "const string \fBbottom\fP = 'bottom'"
.br
.ti -1c
.RI "const string \fBjustify\fP = 'justify'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines HTML strings 


.SH "Member Data Documentation"
.PP 
.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.A = 'A'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.ABBR = 'ABBR'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.abbr = 'abbr'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.accept = 'accept'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.accesskey = 'accesskey'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.ACRONYM = 'ACRONYM'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.action = 'action'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.ADDRESS = 'ADDRESS'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.align = 'align'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.alink = 'alink'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.alt = 'alt'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.APPLET = 'APPLET'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.archive = 'archive'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.AREA = 'AREA'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.axis = 'axis'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.B = 'B'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.background = 'background'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.BASE = 'BASE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.BASEFONT = 'BASEFONT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.BDO = 'BDO'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.bgcolor = 'bgcolor'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.BIG = 'BIG'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.BLOCKQUOTE = 'BLOCKQUOTE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.BODY = 'BODY'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.border = 'border'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.bordercolor = 'bordercolor'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.bottom = 'bottom'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.BR = 'BR'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.BUTTON = 'BUTTON'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.CAPTION = 'CAPTION'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.cellpadding = 'cellpadding'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.cellspacing = 'cellspacing'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.CENTER = 'CENTER'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.center = 'center'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.char_ = 'char'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.charoff = 'charoff'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.charset = 'charset'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.checked_ = 'checked'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.CITE = 'CITE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.cite = 'cite'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.class_ = 'class'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.classid = 'classid'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.clear = 'clear'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.CODE = 'CODE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.code = 'code'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.codebase = 'codebase'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.codetype = 'codetype'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.COL = 'COL'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.COLGROUP = 'COLGROUP'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.color = 'color'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.cols = 'cols'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.colspan = 'colspan'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.compact = 'compact'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.content = 'content'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.coords = 'coords'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.data = 'data'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.datetime = 'datetime'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.DD = 'DD'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.declare = 'declare'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.defer = 'defer'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.DEL = 'DEL'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.DFN = 'DFN'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.DIR = 'DIR'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.dir = 'dir'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.disabled = 'disabled'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.DIV = 'DIV'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.DL = 'DL'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.DT = 'DT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.EM = 'EM'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.enctype = 'enctype'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.face = 'face'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.FIELDSET = 'FIELDSET'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.FONT = 'FONT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.for_ = 'for'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.FORM = 'FORM'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.FRAME = 'FRAME'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.frame = 'frame'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.frameborder = 'frameborder'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.FRAMESET = 'FRAMESET'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.H1 = 'H1'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.H2 = 'H2'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.H3 = 'H3'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.H4 = 'H4'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.H5 = 'H5'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.H6 = 'H6'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.HEAD = 'HEAD'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.headers = 'headers'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.height = 'height'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.HR = 'HR'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.href = 'href'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.hreflang = 'hreflang'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.hspace = 'hspace'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.HTML = 'HTML'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.http_equiv = 'http\-equiv'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.I = 'I'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.id = 'id'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.IFRAME = 'IFRAME'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.IMG = 'IMG'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.INPUT = 'INPUT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.INS = 'INS'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.ISINDEX = 'ISINDEX'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.ismap = 'ismap'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.justify = 'justify'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.KBD = 'KBD'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.LABEL = 'LABEL'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.label = 'label'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.lang = 'lang'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.language = 'language'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.left = 'left'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.LEGEND = 'LEGEND'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.LI = 'LI'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.LINK = 'LINK'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.link = 'link'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.longdesc = 'longdesc'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.MAP = 'MAP'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.marginheight = 'marginheight'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.marginwidth = 'marginwidth'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.maxlength = 'maxlength'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.media = 'media'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.MENU = 'MENU'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.META = 'META'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.method = 'method'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.middle = 'middle'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.multiple = 'multiple'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.name = 'name'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.NOFRAMES = 'NOFRAMES'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.nohref = 'nohref'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.noresize = 'noresize'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.NOSCRIPT = 'NOSCRIPT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.noshade = 'noshade'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.nowrap = 'nowrap'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.OBJECT = 'OBJECT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.object_ = 'object'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.OL = 'OL'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onblur = 'onblur'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onchange = 'onchange'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onclick = 'onclick'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.ondblclick = 'ondblclick'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onfocus = 'onfocus'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onkeydown = 'onkeydown'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onkeypress = 'onkeypress'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onkeyup = 'onkeyup'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onload = 'onload'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onmousedown = 'onmousedown'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onmousemove = 'onmousemove'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onmouseout = 'onmouseout'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onmouseover = 'onmouseover'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onmouseup = 'onmouseup'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onreset = 'onreset'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onselect = 'onselect'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onsubmit = 'onsubmit'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.onunload = 'onunload'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.OPTGROUP = 'OPTGROUP'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.OPTION = 'OPTION'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.P = 'P'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.PARAM = 'PARAM'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.PRE = 'PRE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.profile = 'profile'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.prompt = 'prompt'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.Q = 'Q'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.readonly_ = 'readonly'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.rel = 'rel'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.rev = 'rev'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.right = 'right'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.rows = 'rows'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.rowspan = 'rowspan'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.rules = 'rules'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.S = 'S'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.SAMP = 'SAMP'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.scheme = 'scheme'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.scope = 'scope'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.SCRIPT = 'SCRIPT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.scrolling = 'scrolling'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.SELECT = 'SELECT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.selected = 'selected'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.shape = 'shape'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.size = 'size'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.SMALL = 'SMALL'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.SPAN = 'SPAN'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.span = 'span'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.src = 'src'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.standby = 'standby'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.start = 'start'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.STRIKE = 'STRIKE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.STRONG = 'STRONG'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.STYLE = 'STYLE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.style = 'style'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.SUB = 'SUB'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.summary = 'summary'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.SUP = 'SUP'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.tabindex = 'tabindex'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TABLE = 'TABLE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.target = 'target'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TBODY = 'TBODY'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TD = 'TD'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.text = 'text'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TEXTAREA = 'TEXTAREA'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TFOOT = 'TFOOT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TH = 'TH'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.THEAD = 'THEAD'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TITLE = 'TITLE'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.title = 'title'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.top = 'top'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TR = 'TR'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.TT = 'TT'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.type = 'type'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.U = 'U'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.UL = 'UL'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.usemap = 'usemap'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.valign = 'valign'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.value = 'value'\fC [static]\fP"

.SS "const string interface System\&.Drawing\&.Html\&.HtmlConstants\&.valuetype\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.VAR = 'VAR'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.version = 'version'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.vlink = 'vlink'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.vspace = 'vspace'\fC [static]\fP"

.SS "const string System\&.Drawing\&.Html\&.HtmlConstants\&.width = 'width'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
