.TH "System" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDrawing\fP"
.br
.ti -1c
.RI "namespace \fBWeb\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCatchWrapper\fP"
.br
.ti -1c
.RI "class \fBConsoleEx\fP"
.br
.RI "Console extension methods, particularly writing out text and lines easily in a particular colour and setting background text\&. Also sses the nuget package ColorFul\&.Console so you can utilise System\&.Drawing\&.Color rather just the standard few ConsoleColor list\&. You can also use hex strings and even convert text to ASCII art\&. "
.ti -1c
.RI "class \fBEncodingExtensions\fP"
.br
.RI "String encoding methods (i\&.e\&. to ASCII) "
.ti -1c
.RI "class \fBExtensions\fP"
.br
.RI "Application Extension methods "
.ti -1c
.RI "class \fBProcessExtensions\fP"
.br
.RI "Process object extensions methods\&. You will likely need to use impersonatation when calling\&. "
.ti -1c
.RI "class \fBTryWrapper\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
