.TH "System.Drawing.Html.CssBlock" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Drawing.Html.CssBlock \- Represents a block of CSS property values  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCssBlock\fP (string blockSource)"
.br
.RI "Creates a new block from the block's source "
.ti -1c
.RI "void \fBAssignTo\fP (\fBCssBox\fP b)"
.br
.RI "Asigns the style on this block o the specified box "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< string, string > \fBProperties\fP\fC [get]\fP"
.br
.RI "Gets the properties and its values "
.ti -1c
.RI "Dictionary< PropertyInfo, string > \fBPropertyValues\fP\fC [get]\fP"
.br
.RI "Gets the dictionary with property-ready values "
.ti -1c
.RI "string \fBBlockSource\fP\fC [get]\fP"
.br
.RI "Gets the block's source "
.in -1c
.SH "Detailed Description"
.PP 
Represents a block of CSS property values 

To learn more about CSS blocks visit CSS spec: http://www.w3.org/TR/CSS21/syndata.html#block 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "System\&.Drawing\&.Html\&.CssBlock\&.CssBlock (string blockSource)"

.PP
Creates a new block from the block's source 
.PP
\fBParameters\fP
.RS 4
\fIblockSource\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void System\&.Drawing\&.Html\&.CssBlock\&.AssignTo (\fBCssBox\fP b)"

.PP
Asigns the style on this block o the specified box 
.PP
\fBParameters\fP
.RS 4
\fIb\fP 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string System\&.Drawing\&.Html\&.CssBlock\&.BlockSource\fC [get]\fP"

.PP
Gets the block's source 
.SS "Dictionary<string, string> System\&.Drawing\&.Html\&.CssBlock\&.Properties\fC [get]\fP"

.PP
Gets the properties and its values 
.SS "Dictionary<PropertyInfo, string> System\&.Drawing\&.Html\&.CssBlock\&.PropertyValues\fC [get]\fP"

.PP
Gets the dictionary with property-ready values 

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
