.TH "System.Drawing.Html.CssPropertyAttribute" 3 "Sun Oct 18 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Drawing.Html.CssPropertyAttribute \- Used to mark a property as a Css property\&. The \fBName\fP property is used to specify the oficial CSS name  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCssPropertyAttribute\fP (string name)"
.br
.RI "Creates a new \fBCssPropertyAttribute\fP "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name of the CSS property "
.in -1c
.SH "Detailed Description"
.PP 
Used to mark a property as a Css property\&. The \fBName\fP property is used to specify the oficial CSS name 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "System\&.Drawing\&.Html\&.CssPropertyAttribute\&.CssPropertyAttribute (string name)"

.PP
Creates a new \fBCssPropertyAttribute\fP 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name of the Css property
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string System\&.Drawing\&.Html\&.CssPropertyAttribute\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name of the CSS property 

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
