.TH "System.Drawing.Html.CssAnonymousBox" 3 "Sat Oct 10 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.Drawing.Html.CssAnonymousBox \- Represents an anonymous inline box  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystem\&.Drawing\&.Html\&.CssBox\fP\&.
.PP
Inherited by \fBSystem\&.Drawing\&.Html\&.CssAnonymousSpaceBox\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCssAnonymousBox\fP (\fBCssBox\fP parentBox)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents an anonymous inline box 

To learn more about anonymous inline boxes visit: http://www.w3.org/TR/CSS21/visuren.html#anonymous 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "System\&.Drawing\&.Html\&.CssAnonymousBox\&.CssAnonymousBox (\fBCssBox\fP parentBox)"


.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
