.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Streams/ThrottledStream.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Streams/ThrottledStream.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Streams\&.ThrottledStream\fP"
.br
.RI "Throttle a stream -> Very useful for throttle HttpWebRequest uploads / downloads\&. "
.ti -1c
.RI "class \fBJBToolkit\&.Streams\&.ThrottledStream\&.ThrottleStreamOutput\fP"
.br
.RI "Object which can be passed into the constructor which stores the current 'bytes per second' and 'percentage complete'\&. Can also utilise the 'ThrottleStreamOutputEvent' "
.ti -1c
.RI "class \fBJBToolkit\&.Streams\&.ThrottledStream\&.ThrottleStreamOutputEventArgs\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Streams\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
