.TH "ToolTip" 3 "Mon Aug 31 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolTip
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.WinForms\&.CustomToolTip\fP, and \fBJBToolkit\&.WinForms\&.HtmlToolTip\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
