.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/XmlDoc/Converters/WordToHtml.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/XmlDoc/Converters/WordToHtml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.XmlDoc\&.Converters\&.OfficeHtmlPdfImageConverter\fP"
.br
.RI "Uses a decent 3rd party command line tool to perform a bulk 'Document to PDF Conversion' (quickly - multi-threaded) Will convert typical MS Office documents (docx, xlsx, msg, pptx, vsd, pub and more), images, html and text files it encounters to PDF\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\&.Converters\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
