.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/XmlDoc/MailMerge/WordInteropMailMerge.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/XmlDoc/MailMerge/WordInteropMailMerge.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.XmlDoc\&.MailMerge\&.WordInteropMailMerge\fP"
.br
.RI "Uses OpenXML to perform a Word Mail Merge\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.XmlDoc\&.MailMerge\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBDataTable\fP = System\&.Data\&.DataTable"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBDataTable\fP =  System\&.Data\&.DataTable"

.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
