.TH "D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Zip/ZipCompression.cs" 3 "Thu Oct 1 2020" "JB.Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/JB.Toolkit/JB.Toolkit/Zip/ZipCompression.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Zip\&.FilePathAndBytesCollection\fP"
.br
.RI "A basic dictionary of the filename to save within the zip file and the bytes of that file "
.ti -1c
.RI "class \fBJBToolkit\&.Zip\&.FilePathAndBytes\fP"
.br
.RI "Filename to store within zip file and it's file as a byte array "
.ti -1c
.RI "class \fBJBToolkit\&.Zip\&.ZipCompression\fP"
.br
.RI "Contains multiple method for saving zip files or returning a zip file as a stream "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Zip\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJBToolkit\&.Zip\&.ZipCompressionLevel\fP { \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.None\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Fast\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Best\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level0\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level1\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level2\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level3\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level4\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level5\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level6\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level7\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level8\fP, \fBJBToolkit\&.Zip\&.ZipCompressionLevel\&.Level9\fP }"
.br
.ti -1c
.RI "enum \fBJBToolkit\&.Zip\&.ZipCompressionMethod\fP { \fBJBToolkit\&.Zip\&.ZipCompressionMethod\&.None\fP, \fBJBToolkit\&.Zip\&.ZipCompressionMethod\&.Deflate\fP, \fBJBToolkit\&.Zip\&.ZipCompressionMethod\&.BZip2\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JB\&.Toolkit from the source code\&.
