var searchData=
[
  ['safefilestream_2276',['SafeFileStream',['../d9/d2a/class_j_b_toolkit_1_1_streams_1_1_safe_file_stream.html',1,'JBToolkit::Streams']]],
  ['safehandlezeroorminusoneisinvalid_2277',['SafeHandleZeroOrMinusOneIsInvalid',['../db/d0f/class_safe_handle_zero_or_minus_one_is_invalid.html',1,'']]],
  ['scrollablecontrol_2278',['ScrollableControl',['../dc/da7/class_scrollable_control.html',1,'']]],
  ['scrollinglistbox_2279',['ScrollingListBox',['../dc/d04/class_j_b_toolkit_1_1_win_forms_1_1_scrolling_list_box.html',1,'JBToolkit::WinForms']]],
  ['servicehelper_2280',['ServiceHelper',['../dc/d35/class_j_b_toolkit_1_1_windows_1_1_service_helper.html',1,'JBToolkit::Windows']]],
  ['sharedmemoryclient_2281',['SharedMemoryClient',['../d8/d74/class_j_b_toolkit_1_1_inter_process_comms_1_1_memory_mapped_files_1_1_shared_memory_client.html',1,'JBToolkit::InterProcessComms::MemoryMappedFiles']]],
  ['sharedmemoryserver_2282',['SharedMemoryServer',['../db/d92/class_j_b_toolkit_1_1_inter_process_comms_1_1_memory_mapped_files_1_1_shared_memory_server.html',1,'JBToolkit::InterProcessComms::MemoryMappedFiles']]],
  ['sharepointrequestresult_2283',['SharePointRequestResult',['../d8/d22/class_j_b_toolkit_1_1_share_point_1_1_share_point_request_result.html',1,'JBToolkit::SharePoint']]],
  ['socketclient_2284',['SocketClient',['../dc/d1d/class_j_b_toolkit_1_1_inter_process_comms_1_1_sockets_1_1_socket_client.html',1,'JBToolkit::InterProcessComms::Sockets']]],
  ['socketserver_2285',['SocketServer',['../dd/dc8/class_j_b_toolkit_1_1_inter_process_comms_1_1_sockets_1_1_socket_server.html',1,'JBToolkit::InterProcessComms::Sockets']]],
  ['southwest_2286',['Southwest',['../d7/d84/class_j_b_toolkit_1_1_googe_api_1_1_geocoding_1_1_southwest.html',1,'JBToolkit::GoogeApi::Geocoding']]],
  ['spacingbox_2287',['SpacingBox',['../dd/da3/class_system_1_1_drawing_1_1_html_1_1_css_table_1_1_spacing_box.html',1,'System::Drawing::Html::CssTable']]],
  ['stringencrypt_2288',['StringEncrypt',['../d0/d71/class_j_b_toolkit_1_1_encryption_1_1_string_encrypt.html',1,'JBToolkit::Encryption']]],
  ['stringwalker_2289',['StringWalker',['../d3/d0c/class_j_b_toolkit_1_1_extensions_1_1_source_code_1_1_source_code_formatter_1_1_lenient_json_formatter_1_1_string_walker.html',1,'JBToolkit::Extensions::SourceCode::SourceCodeFormatter::LenientJsonFormatter']]],
  ['successdbcommandresult_2290',['SuccessDBCommandResult',['../d9/dee/class_j_b_toolkit_1_1_database_1_1_db_result_1_1_success_d_b_command_result.html',1,'JBToolkit::Database::DbResult']]],
  ['successemailresult_2291',['SuccessEmailResult',['../df/d38/class_j_b_toolkit_1_1_web_1_1_success_email_result.html',1,'JBToolkit::Web']]]
];
